"""Quality-affecting constants shared by Phase 1 execution and recipe evidence."""

FINAL_COVERAGE_FADE_TAIL_MAX_FRAMES = 5

POST_REFINEMENT_SPARSE_COMPACT_POLICY_VERSION = (
    "post_refinement_sparse_compact_text_consensus_v1"
)
POST_REFINEMENT_SPARSE_COMPACT_MAX_WIDTH_FRAC = 0.08
POST_REFINEMENT_SPARSE_COMPACT_MAX_HEIGHT_FRAC = 0.065
POST_REFINEMENT_VISUAL_NORMALIZED_HEIGHT = 64
POST_REFINEMENT_TEXTURE_MAX_LAPLACIAN_VARIANCE = 150.0
POST_REFINEMENT_TEXTURE_MAX_EDGE_DENSITY = 0.10
POST_REFINEMENT_TEXTURE_MIN_SATURATION = 120.0

RESIDUAL_HARDSUB_RECOVERY_POLICY_VERSION = "residual_hardsub_recovery_v1"
RESIDUAL_HARDSUB_MIN_FRAMES = 3
RESIDUAL_HARDSUB_MAX_FRAME_GAP = 2
RESIDUAL_HARDSUB_GENERIC_MIN_CY_FRAC = 0.84
RESIDUAL_HARDSUB_MIN_WIDTH_FRAC = 0.12
RESIDUAL_HARDSUB_MAX_HEIGHT_FRAC = 0.11

PERSPECTIVE_UI_PROVENANCE_POLICY_VERSION = "perspective_ui_provenance_v2"
PERSPECTIVE_UI_MIN_COHORT = 7
PERSPECTIVE_UI_MIN_X_SPREAD_FRAC = 0.20
PERSPECTIVE_UI_MIN_Y_SPREAD_FRAC = 0.15
PERSPECTIVE_UI_SCENE_MIN_COHORT = 4
PERSPECTIVE_UI_SCENE_MAX_GAP_FRAMES = 30
PERSPECTIVE_UI_SCENE_MIN_X_SPREAD_FRAC = 0.05
PERSPECTIVE_UI_SCENE_MIN_Y_SPREAD_FRAC = 0.15
