from enum import StrEnum


class SourcePlatformEnum(StrEnum):
    DOUYIN = "DOUYIN"


class SourceProfileStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"


class CrawlSessionStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SourceVideoStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    FILTERED_IN = "FILTERED_IN"
    REJECTED = "REJECTED"
    APPROVED_FOR_DOWNLOAD = "APPROVED_FOR_DOWNLOAD"
    DOWNLOADED = "DOWNLOADED"
    AI_ANALYZED = "AI_ANALYZED"
    NEEDS_SCRIPT_REVIEW = "NEEDS_SCRIPT_REVIEW"
    NEEDS_OCR_REVIEW = "NEEDS_OCR_REVIEW"
    READY_FOR_RENDER = "READY_FOR_RENDER"
    RENDERING = "RENDERING"
    READY_FINAL_REVIEW = "READY_FINAL_REVIEW"
    EXPORTED = "EXPORTED"
    PUBLISH_READY = "PUBLISH_READY"
    FAILED = "FAILED"


class DouyinAccountConnectionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INVALID = "INVALID"
    EXPIRED = "EXPIRED"
    DISABLED = "DISABLED"
    BLOCKED = "BLOCKED"


class DouyinAccountHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    STALE = "STALE"
    EXPIRING_SOON = "EXPIRING_SOON"
    INVALID = "INVALID"
    EXPIRED = "EXPIRED"
    BLOCKED = "BLOCKED"
    DISABLED = "DISABLED"
    UNKNOWN = "UNKNOWN"


class DouyinAccountWarningLevel(StrEnum):
    NONE = "NONE"
    INFO = "INFO"
    WARN = "WARN"
    BLOCK = "BLOCK"


class DouyinBrowserConnectSessionStatus(StrEnum):
    PENDING = "PENDING"
    LAUNCHING_BROWSER = "LAUNCHING_BROWSER"
    WAITING_FOR_LOGIN = "WAITING_FOR_LOGIN"
    CAPTURING_SESSION = "CAPTURING_SESSION"
    VALIDATING = "VALIDATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class CandidateStatus(StrEnum):
    NEW = "NEW"
    SHORTLISTED = "SHORTLISTED"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"


class CaptureSessionStatus(StrEnum):
    RECEIVED = "RECEIVED"
    ENRICHING = "ENRICHING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    PARTIALLY_PROMOTED = "PARTIALLY_PROMOTED"
    PROMOTED = "PROMOTED"
    FAILED = "FAILED"


class CapturedItemStatus(StrEnum):
    RAW = "RAW"
    ENRICHED = "ENRICHED"
    READY = "READY"
    NEEDS_ENRICHMENT = "NEEDS_ENRICHMENT"
    PREVIEW_MISSING = "PREVIEW_MISSING"
    DUPLICATE = "DUPLICATE"
    EXCLUDED = "EXCLUDED"
    PROMOTED = "PROMOTED"
    FAILED = "FAILED"


class IntakeEvaluationStatus(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    MATCHED = "MATCHED"
    FILTERED_OUT = "FILTERED_OUT"
    MISSING_REQUIREMENTS = "MISSING_REQUIREMENTS"
    EVALUATION_ERROR = "EVALUATION_ERROR"


class ReviewDecisionStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    NEEDS_CHANGES = "NEEDS_CHANGES"
    SUPERSEDED = "SUPERSEDED"


class ReupQueueStatus(StrEnum):
    READY_FOR_PROCESSING = "READY_FOR_PROCESSING"
    WAITING_FOR_MEDIA = "WAITING_FOR_MEDIA"
    WAITING_FOR_METADATA = "WAITING_FOR_METADATA"
    PROCESSING = "PROCESSING"
    READY_TO_EXPORT = "READY_TO_EXPORT"
    EXPORT_PACKAGE_CREATED = "EXPORT_PACKAGE_CREATED"
    READY_TO_PUBLISH = "READY_TO_PUBLISH"
    PUBLISH_HANDOFF_CREATED = "PUBLISH_HANDOFF_CREATED"
    FAILED_NEEDS_ATTENTION = "FAILED_NEEDS_ATTENTION"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReupQueueAction(StrEnum):
    START_PROCESSING = "START_PROCESSING"
    MARK_MEDIA_READY = "MARK_MEDIA_READY"
    MARK_BLOCKED = "MARK_BLOCKED"
    HOLD = "HOLD"
    RESUME = "RESUME"
    RETRY = "RETRY"
    CANCEL = "CANCEL"
    MARK_COMPLETED = "MARK_COMPLETED"
    DISMISS = "DISMISS"


class ReupQueueMediaPrepStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    WAITING_FOR_MEDIA = "WAITING_FOR_MEDIA"
    WAITING_FOR_METADATA = "WAITING_FOR_METADATA"
    READY_FOR_EXPORT = "READY_FOR_EXPORT"
    BLOCKED = "BLOCKED"


class ReupQueueBatchAction(StrEnum):
    START_PROCESSING = "START_PROCESSING"
    HOLD = "HOLD"
    RESUME = "RESUME"
    RETRY = "RETRY"
    CANCEL = "CANCEL"
    MARK_MEDIA_READY = "MARK_MEDIA_READY"
    CREATE_EXPORT_PACKAGE = "CREATE_EXPORT_PACKAGE"
    CREATE_PUBLISH_HANDOFF = "CREATE_PUBLISH_HANDOFF"
    DISMISS = "DISMISS"
    PURGE = "PURGE"


class ExportPackageStatus(StrEnum):
    DRAFT = "DRAFT"
    READY_FOR_HANDOFF = "READY_FOR_HANDOFF"
    HANDOFF_CREATED = "HANDOFF_CREATED"
    FAILED_NEEDS_ATTENTION = "FAILED_NEEDS_ATTENTION"
    CANCELLED = "CANCELLED"


class PublishHandoffStatus(StrEnum):
    DRAFT = "DRAFT"
    READY_FOR_OPERATOR = "READY_FOR_OPERATOR"
    ACCEPTED = "ACCEPTED"
    FAILED_NEEDS_ATTENTION = "FAILED_NEEDS_ATTENTION"
    CANCELLED = "CANCELLED"


class MediaAssetType(StrEnum):
    SOURCE_VIDEO = "SOURCE_VIDEO"
    SOURCE_VIDEO_RAW = "SOURCE_VIDEO_RAW"
    SOURCE_VIDEO_PREVIEW = "SOURCE_VIDEO_PREVIEW"
    SOURCE_AUDIO = "SOURCE_AUDIO"
    SOURCE_AUDIO_EXTRACT = "SOURCE_AUDIO_EXTRACT"
    AUDIO_VOCAL_STEM = "AUDIO_VOCAL_STEM"
    AUDIO_BACKGROUND_STEM = "AUDIO_BACKGROUND_STEM"
    AUDIO_ANALYSIS_METADATA = "AUDIO_ANALYSIS_METADATA"
    THUMBNAIL = "THUMBNAIL"
    METADATA_JSON = "METADATA_JSON"
    SOURCE_CAPTION_RAW = "SOURCE_CAPTION_RAW"
    TRANSCRIPT_JSON = "TRANSCRIPT_JSON"
    TRANSLATION_DRAFT_JSON = "TRANSLATION_DRAFT_JSON"
    TTS_AUDIO_CLIP = "TTS_AUDIO_CLIP"
    TTS_AUDIO_JOINED = "TTS_AUDIO_JOINED"
    SUBTITLE_JSON = "SUBTITLE_JSON"
    SUBTITLE_SRT = "SUBTITLE_SRT"
    SUBTITLE_ASS = "SUBTITLE_ASS"
    RENDER_PREP_MANIFEST = "RENDER_PREP_MANIFEST"
    FINAL_RENDER_VIDEO = "FINAL_RENDER_VIDEO"
    RENDER_LOG = "RENDER_LOG"
    RENDER_DEBUG_JSON = "RENDER_DEBUG_JSON"
    RENDER_MANIFEST = "RENDER_MANIFEST"
    TRANSCRIPT = "TRANSCRIPT"
    TRANSLATION = "TRANSLATION"
    SUBTITLE = "SUBTITLE"
    OCR_FRAME = "OCR_FRAME"
    OCR_EVENTS = "OCR_EVENTS"
    CLEANED_VIDEO = "CLEANED_VIDEO"
    TEMP_FILE = "TEMP_FILE"
    RENDER_OUTPUT = "RENDER_OUTPUT"
    RENDERED_VIDEO = "RENDERED_VIDEO"
    EXPORT_PACKAGE = "EXPORT_PACKAGE"


class MediaAssetStatus(StrEnum):
    PLANNED = "PLANNED"
    AVAILABLE = "AVAILABLE"
    PROCESSING = "PROCESSING"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class JobType(StrEnum):
    CRAWL_PROFILE = "CRAWL_PROFILE"
    VALIDATE_DOUYIN_ACCOUNT = "VALIDATE_DOUYIN_ACCOUNT"
    REVALIDATE_STALE_DOUYIN_ACCOUNTS = "REVALIDATE_STALE_DOUYIN_ACCOUNTS"
    SCORE_CANDIDATES = "SCORE_CANDIDATES"
    DOWNLOAD_VIDEO = "DOWNLOAD_VIDEO"
    ANALYZE_AUDIO = "ANALYZE_AUDIO"
    ANALYZE_OCR = "ANALYZE_OCR"
    BUILD_TRANSLATION_DRAFT = "BUILD_TRANSLATION_DRAFT"
    SYNTHESIZE_TTS = "SYNTHESIZE_TTS"
    RENDER_PREVIEW = "RENDER_PREVIEW"
    RENDER_FINAL = "RENDER_FINAL"
    PUBLISH_CONTENT = "PUBLISH_CONTENT"
    REFRESH_PUBLISH_STATUS = "REFRESH_PUBLISH_STATUS"
    RECONCILE_PUBLISH_ATTEMPT = "RECONCILE_PUBLISH_ATTEMPT"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
    FAILED = "FAILED"
    RETRYABLE = "RETRYABLE"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"


class JobStepStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_FOR_INPUT = "WAITING_FOR_INPUT"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    COMPLETED = "COMPLETED"


class TranscriptSegmentStatus(StrEnum):
    DRAFT = "DRAFT"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class OcrObjectStatus(StrEnum):
    DETECTED = "DETECTED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class RenderOutputStatus(StrEnum):
    PLANNED = "PLANNED"
    RENDERING = "RENDERING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class PublishDraftStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    SCHEDULED = "SCHEDULED"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    NEEDS_ATTENTION = "NEEDS_ATTENTION"
    ARCHIVED = "ARCHIVED"


class PublishTargetPlatform(StrEnum):
    TIKTOK = "TIKTOK"
    FACEBOOK_REELS = "FACEBOOK_REELS"
    YOUTUBE_SHORTS = "YOUTUBE_SHORTS"


class PlatformAccountStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    INVALID = "INVALID"
    ARCHIVED = "ARCHIVED"


class PublishAttemptStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    UPLOADING = "UPLOADING"
    PUBLISHING = "PUBLISHING"
    AWAITING_PLATFORM_CONFIRMATION = "AWAITING_PLATFORM_CONFIRMATION"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    NEEDS_RECONCILIATION = "NEEDS_RECONCILIATION"
    RECONCILING = "RECONCILING"
    RECONCILED = "RECONCILED"
    CANCELLED = "CANCELLED"


class ExternalPublicationStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    PROCESSING = "PROCESSING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    REMOVED = "REMOVED"
    NOT_FOUND = "NOT_FOUND"
    PARTIALLY_CONFIRMED = "PARTIALLY_CONFIRMED"


class PublishReconciliationStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED = "REQUIRED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED_SUCCESS = "RESOLVED_SUCCESS"
    RESOLVED_FAILURE = "RESOLVED_FAILURE"
    UNRESOLVED = "UNRESOLVED"


class RiskFlagType(StrEnum):
    COPYRIGHT = "COPYRIGHT"
    WATERMARK = "WATERMARK"
    LOW_QUALITY = "LOW_QUALITY"
    DUPLICATE = "DUPLICATE"
    POLICY = "POLICY"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    AUDIO_COPYRIGHT_RISK = "AUDIO_COPYRIGHT_RISK"
    WATERMARK_RISK = "WATERMARK_RISK"
    BRAND_LOGO_RISK = "BRAND_LOGO_RISK"
    CELEBRITY_PERSONA_RISK = "CELEBRITY_PERSONA_RISK"
    OCR_DENSITY_RISK = "OCR_DENSITY_RISK"
    SPEECH_QUALITY_RISK = "SPEECH_QUALITY_RISK"
    PROCESSING_COMPLEXITY_RISK = "PROCESSING_COMPLEXITY_RISK"
    PLATFORM_POLICY_RISK = "PLATFORM_POLICY_RISK"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


class RiskSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    BLOCKING = "BLOCKING"


class RiskFlagStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    WAIVED = "WAIVED"
    REJECTED = "REJECTED"


class RiskTargetType(StrEnum):
    SOURCE_VIDEO = "SOURCE_VIDEO"
    RENDER_OUTPUT = "RENDER_OUTPUT"
    PUBLISH_DRAFT = "PUBLISH_DRAFT"


class OperatorRiskDecisionType(StrEnum):
    CONTINUE = "CONTINUE"
    NEEDS_FIX = "NEEDS_FIX"
    REJECT = "REJECT"
    ACCEPT_WITH_WARNING = "ACCEPT_WITH_WARNING"


class OperatorFeedbackTargetType(StrEnum):
    SOURCE_VIDEO = "SOURCE_VIDEO"
    RENDER_OUTPUT = "RENDER_OUTPUT"
    PUBLISH_DRAFT = "PUBLISH_DRAFT"
    PUBLISH_ATTEMPT = "PUBLISH_ATTEMPT"


class OperatorFeedbackQualityLabel(StrEnum):
    GOOD = "GOOD"
    ACCEPTABLE = "ACCEPTABLE"
    WEAK = "WEAK"


class PublishConfidenceLabel(StrEnum):
    SCALABLE = "SCALABLE"
    NEEDS_IMPROVEMENT = "NEEDS_IMPROVEMENT"
    DO_NOT_REUSE_PATTERN = "DO_NOT_REUSE_PATTERN"


class OperatorFeedbackRootCause(StrEnum):
    SOURCE_SELECTION_ISSUE = "SOURCE_SELECTION_ISSUE"
    TRANSCRIPT_QUALITY_ISSUE = "TRANSCRIPT_QUALITY_ISSUE"
    TTS_ISSUE = "TTS_ISSUE"
    SUBTITLE_ISSUE = "SUBTITLE_ISSUE"
    RENDER_ISSUE = "RENDER_ISSUE"
    PUBLISH_ISSUE = "PUBLISH_ISSUE"
    RISK_FALSE_POSITIVE = "RISK_FALSE_POSITIVE"
    CTA_CAPTION_ISSUE = "CTA_CAPTION_ISSUE"
    OTHER = "OTHER"


class PublishAccountAssignmentStatus(StrEnum):
    UNASSIGNED = "UNASSIGNED"
    ASSIGNED = "ASSIGNED"
    OVERRIDDEN = "OVERRIDDEN"


class PublishRoutingRuleStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ARCHIVED = "ARCHIVED"


class PlatformAccountHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"
    HELD = "HELD"
