from __future__ import annotations

import json
import logging
import shutil
import subprocess
import tempfile
from pathlib import Path

from src.core.settings import get_settings
from src.downloaders.douyin_video_resolver import DouyinVideoResolveRequest, ResolvedDouyinVideo
from src.downloaders.errors import DownloadError, DownloadErrorCode

logger = logging.getLogger(__name__)

_NETSCAPE_COOKIE_EXPIRY = "2147483647"


def yt_dlp_no_logo_format_selector(format_selector: str, *, strict: bool) -> str:
    """In strict mode prefer play/best streams — Douyin download/* often burns in the logo."""
    selector = (format_selector or "").strip() or "bestvideo*+bestaudio/best"
    if not strict:
        return selector
    parts = [part.strip() for part in selector.split("/") if part.strip()]
    play_parts = [part for part in parts if "download" not in part.lower()]
    return "/".join(play_parts) if play_parts else "bestvideo*+bestaudio/best"


def is_yt_dlp_no_logo_format(format_id: str | None, *, info: dict | None = None) -> bool:
    """True when the selected yt-dlp format is not a Douyin download/* (logo) family."""
    tokens: list[str] = []
    if format_id:
        tokens.append(str(format_id).lower())
    if info:
        tokens.append(str(info.get("format_id") or "").lower())
        tokens.append(str(info.get("format") or "").lower())
        for fmt in info.get("requested_formats") or []:
            if not isinstance(fmt, dict):
                continue
            tokens.append(str(fmt.get("format_id") or "").lower())
            tokens.append(str(fmt.get("format_note") or "").lower())
    meaningful = [token for token in tokens if token]
    if not meaningful:
        return False
    if any("download" in token for token in meaningful):
        return False
    return True


def cookie_header_to_netscape_lines(cookie_header: str) -> list[str]:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by reup-douyin",
        "",
    ]
    for part in cookie_header.split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        name, value = part.split("=", 1)
        name = name.strip()
        value = value.strip()
        if not name:
            continue
        lines.append(f".douyin.com\tTRUE\t/\tTRUE\t{_NETSCAPE_COOKIE_EXPIRY}\t{name}\t{value}")
    return lines


def write_netscape_cookie_file(cookie_header: str, path: Path) -> None:
    lines = cookie_header_to_netscape_lines(cookie_header)
    if len(lines) <= 3:
        raise DownloadError(DownloadErrorCode.RESOLVE_FAILED, "Douyin session cookie header is empty or invalid")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _playwright_cookie_expiry(cookie: dict) -> str:
    expires = cookie.get("expires")
    if isinstance(expires, (int, float)) and expires > 0:
        return str(int(expires))
    return _NETSCAPE_COOKIE_EXPIRY


def playwright_cookies_to_netscape_lines(cookies: list[dict]) -> list[str]:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by reup-douyin (playwright)",
        "",
    ]
    for cookie in cookies:
        domain = str(cookie.get("domain", "")).strip()
        name = str(cookie.get("name", "")).strip()
        value = str(cookie.get("value", "")).strip()
        if not domain or not name or "douyin.com" not in domain.lower():
            continue
        path = str(cookie.get("path", "/") or "/")
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        lines.append(
            f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{_playwright_cookie_expiry(cookie)}\t{name}\t{value}"
        )
    return lines


def write_netscape_cookie_file_from_playwright(cookies: list[dict], path: Path) -> None:
    lines = playwright_cookies_to_netscape_lines(cookies)
    if len(lines) <= 3:
        raise DownloadError(DownloadErrorCode.RESOLVE_FAILED, "Playwright Douyin cookies are empty or invalid")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _load_yt_dlp_info_json(output_path: Path) -> dict | None:
    info_path = output_path.with_name(f"{output_path.stem}.info.json")
    if not info_path.is_file():
        return None
    try:
        payload = json.loads(info_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return payload if isinstance(payload, dict) else None


class YtDlpDouyinVideoResolver:
    def __init__(
        self,
        *,
        binary: str | None = None,
        format_selector: str | None = None,
        timeout_seconds: int | None = None,
    ):
        settings = get_settings()
        self.binary = binary or settings.douyin_yt_dlp_binary
        self.format_selector = format_selector or settings.douyin_yt_dlp_format
        self.timeout_seconds = timeout_seconds or settings.douyin_yt_dlp_timeout_seconds

    def is_available(self) -> bool:
        return shutil.which(self.binary) is not None

    def resolve(self, request: DouyinVideoResolveRequest) -> ResolvedDouyinVideo:
        if not self.is_available():
            raise DownloadError(
                DownloadErrorCode.RESOLVE_FAILED,
                f"yt-dlp binary is not available on PATH: {self.binary}",
            )

        settings = get_settings()
        strict_nologo = not bool(getattr(settings, "douyin_download_allow_watermarked_fallback", False))
        format_selector = yt_dlp_no_logo_format_selector(self.format_selector, strict=strict_nologo)

        page_url = request.page_url or f"https://www.douyin.com/video/{request.aweme_id}"
        with tempfile.TemporaryDirectory(prefix="reup-douyin-yt-dlp-") as tmp_dir:
            tmp_path = Path(tmp_dir)
            output_template = str(tmp_path / "video.%(ext)s")
            command = [
                self.binary,
                "--no-playlist",
                "--no-progress",
                "--write-info-json",
                "-f",
                format_selector,
                "-o",
                output_template,
                page_url,
            ]
            if request.user_agent:
                command.extend(["--add-header", f"User-Agent: {request.user_agent}"])
            command.extend(["--add-header", "Referer:https://www.douyin.com/"])
            cookie_file = tmp_path / "cookies.txt"
            if request.playwright_cookies:
                write_netscape_cookie_file_from_playwright(list(request.playwright_cookies), cookie_file)
                command.extend(["--cookies", str(cookie_file)])
            elif request.session_cookie:
                write_netscape_cookie_file(request.session_cookie, cookie_file)
                command.extend(["--cookies", str(cookie_file)])
            if request.proxy_url:
                command.extend(["--proxy", request.proxy_url])

            logger.info(
                "yt_dlp_download_started",
                extra={
                    "aweme_id": request.aweme_id,
                    "page_url": page_url,
                    "binary": self.binary,
                    "format_selector": format_selector,
                    "strict_nologo": strict_nologo,
                },
            )
            try:
                completed = subprocess.run(
                    command,
                    capture_output=True,
                    text=True,
                    timeout=self.timeout_seconds,
                    check=False,
                )
            except subprocess.TimeoutExpired as exc:
                raise DownloadError(
                    DownloadErrorCode.DOWNLOAD_FAILED,
                    f"yt-dlp timed out after {self.timeout_seconds}s",
                ) from exc

            if completed.returncode != 0:
                stderr = (completed.stderr or completed.stdout or "yt-dlp failed without stderr").strip()
                raise DownloadError(
                    DownloadErrorCode.DOWNLOAD_FAILED,
                    stderr[:500],
                )

            output_files = sorted(tmp_path.glob("video.*"))
            output_files = [path for path in output_files if path.suffix.lower() != ".json"]
            if not output_files:
                raise DownloadError(
                    DownloadErrorCode.VALIDATION_FAILED,
                    "yt-dlp completed without producing a video file",
                )

            output_path = output_files[0]
            content = output_path.read_bytes()
            if not content:
                raise DownloadError(
                    DownloadErrorCode.VALIDATION_FAILED,
                    "yt-dlp produced an empty video file",
                )

            info = _load_yt_dlp_info_json(output_path)
            actual_format_id = None
            height = None
            width = None
            if info:
                actual_format_id = str(info.get("format_id") or "") or None
                height = info.get("height") if isinstance(info.get("height"), int) else None
                width = info.get("width") if isinstance(info.get("width"), int) else None

            # Strict: require info.json evidence of the actual format (do not trust the -f selector string).
            watermark_free = is_yt_dlp_no_logo_format(actual_format_id, info=info)
            if strict_nologo and not watermark_free:
                raise DownloadError(
                    DownloadErrorCode.DOWNLOAD_FAILED,
                    "yt-dlp selected a watermarked format; strict no-logo rejects it. "
                    f"format_id={actual_format_id or 'unknown'}",
                )

            logger.info(
                "yt_dlp_download_completed",
                extra={
                    "aweme_id": request.aweme_id,
                    "bytes": len(content),
                    "filename": output_path.name,
                    "format_id": actual_format_id or format_selector,
                    "watermark_free": watermark_free,
                    "height": height,
                },
            )
            resolver_name = "yt_dlp_browser" if request.playwright_cookies else "yt_dlp"
            return ResolvedDouyinVideo(
                content=content,
                mime_type=_guess_mime_type(output_path.suffix),
                filename=output_path.name,
                resolver_name=resolver_name,
                format_id=actual_format_id or format_selector,
                watermark_free=watermark_free,
                height=height,
                width=width,
            )


def _guess_mime_type(suffix: str) -> str:
    normalized = suffix.lower().lstrip(".")
    if normalized in {"mp4", "m4v"}:
        return "video/mp4"
    if normalized == "webm":
        return "video/webm"
    return "application/octet-stream"
