/** Product Matching Intelligence polish: editorial toolbar v12 + spectrum + review drawer. */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const webSrc = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const queue = readFileSync(resolve(webSrc, "components/operator-routes/AffiliateProductMatchingQueue.tsx"), "utf8");
const cssFull = readFileSync(resolve(webSrc, "app/globals.css"), "utf8");
const en = readFileSync(resolve(webSrc, "lib/i18n/en.json"), "utf8");
const vi = readFileSync(resolve(webSrc, "lib/i18n/vi.json"), "utf8");
const v10Start = cssFull.indexOf("/* Affiliate Matching Editorial v10");
assert.ok(v10Start >= 0, "v10 affiliate matching polish CSS block must exist");
const v10 = cssFull.slice(v10Start, v10Start + 9000);
const spectrumStart = cssFull.indexOf("/* Affiliate Matching Spectrum v11");
assert.ok(spectrumStart >= 0, "v11 affiliate matching spectrum CSS block must exist");
const spectrum = cssFull.slice(spectrumStart, spectrumStart + 7000);
const v12Start = cssFull.indexOf("/* Affiliate Matching Toolbar v12");
assert.ok(v12Start >= 0, "v12 affiliate matching toolbar CSS block must exist");
const v12 = cssFull.slice(v12Start, v12Start + 4500);
const v13Start = cssFull.indexOf("/* Affiliate Matching Table v13");
assert.ok(v13Start >= 0, "v13 affiliate matching table CSS block must exist");
const v13 = cssFull.slice(v13Start, v13Start + 5500);
const v14Start = cssFull.indexOf("/* Affiliate Matching Review v14");
assert.ok(v14Start >= 0, "v14 affiliate matching review CSS block must exist");
const v14 = cssFull.slice(v14Start, v14Start + 5500);
const v15Start = cssFull.indexOf("/* Affiliate Matching Review Split v15");
assert.ok(v15Start >= 0, "v15 affiliate matching review split CSS block must exist");
const v15 = cssFull.slice(v15Start, v15Start + 5500);
const v16Start = cssFull.indexOf("/* Affiliate Matching Review Stack v16");
assert.ok(v16Start >= 0, "v16 affiliate matching review stack CSS block must exist");
const v16 = cssFull.slice(v16Start, v16Start + 5500);
const v17Start = cssFull.indexOf("/* Affiliate Matching Review Inspector v17");
assert.ok(v17Start >= 0, "v17 affiliate matching review inspector CSS block must exist");
const v17 = cssFull.slice(v17Start, v17Start + 6500);
const v18Start = cssFull.indexOf("/* Affiliate Matching Review Full-bleed v18");
assert.ok(v18Start >= 0, "v18 affiliate matching review full-bleed CSS block must exist");
const v18 = cssFull.slice(v18Start, v18Start + 6500);
const v19Start = cssFull.indexOf("/* Affiliate Matching Review Compact v19");
assert.ok(v19Start >= 0, "v19 affiliate matching review compact CSS block must exist");
const v19 = cssFull.slice(v19Start, v19Start + 6500);
const v20Start = cssFull.indexOf("/* Affiliate Matching Review Drawer v20");
assert.ok(v20Start >= 0, "v20 affiliate matching review drawer CSS block must exist");
const v20 = cssFull.slice(v20Start, v20Start + 6500);
const v21Start = cssFull.indexOf("/* Affiliate Matching Review Detail v21");
assert.ok(v21Start >= 0, "v21 affiliate matching review detail CSS block must exist");
const v21 = cssFull.slice(v21Start, v21Start + 7500);
const v22Start = cssFull.indexOf("/* Affiliate Matching Review Dense Fill v22");
assert.ok(v22Start >= 0, "v22 affiliate matching review dense fill CSS block must exist");
const v22 = cssFull.slice(v22Start, v22Start + 5500);
const v23Start = cssFull.indexOf("/* Affiliate Matching Review Info v23");
assert.ok(v23Start >= 0, "v23 affiliate matching review info CSS block must exist");
const v23 = cssFull.slice(v23Start, v23Start + 7500);
const v24Start = cssFull.indexOf("/* Affiliate Matching Review Type Scale v24");
assert.ok(v24Start >= 0, "v24 affiliate matching review type scale CSS block must exist");
const v24 = cssFull.slice(v24Start, v24Start + 5500);

assert.match(queue, /affiliate-matching-page is-v10/, "Matching page must opt into v10 shell");
assert.match(queue, /is-v12/, "Matching page must opt into v12 command toolbar");
assert.match(queue, /is-v13/, "Matching page must opt into v13 dense results table");
assert.match(queue, /is-v24/, "Matching page must opt into v24 review type scale");
assert.match(queue, /WorkItemDetailsDrawer/, "v24 must open review in WorkItemDetailsDrawer");
assert.match(queue, /is-clickable/, "Matched rows must be marked clickable for drawer open");
assert.match(queue, /onClick=\{\s*match\s*\?\s*\(\)\s*=>\s*openItem\(item\)\s*:\s*undefined\s*\}/, "Matched rows must open the review drawer on row click");
assert.match(queue, /stopPropagation/, "Action controls must stopPropagation so row click does not double-toggle");
assert.match(queue, /affiliate-matching-toolbar is-v12/, "v12 must use the command-strip toolbar class");
assert.match(queue, /affiliate-matching-table-wrap is-v13|affiliate-matching-table is-v13/, "v13 must mark the results table shell");
assert.match(queue, /affiliate-matching-review is-v24/, "v24 must mark the type-scaled review body");
assert.match(queue, /affiliate-matching-review__context/, "v24 must show reel/topic context in the drawer header");
assert.match(queue, /affiliate-matching-review__reel/, "v24 must show a reel summary block");
assert.match(queue, /affiliate-matching-review__facts/, "v24 must show selected product facts");
assert.match(queue, /affiliate-matching-review__breakdown/, "v24 must show full score breakdown");
assert.match(queue, /affiliate-matching-review__meta/, "v24 must show match meta details");
assert.match(queue, /footer=\{|affiliate-matching-review__footer/, "v24 must pin decide actions in the drawer footer");
assert.match(queue, /affiliate-matching-review__inspector|affiliate-matching-review__decide/, "v24 must keep inspector picks + decide sections");
assert.match(queue, /affiliate-matching-suggestions__score|suggestions__title/, "v24 must place fit score beside the suggestion title");
assert.doesNotMatch(queue, /affiliate-matching-review-row/, "v20+ must remove the inline table review row");
assert.doesNotMatch(queue, /affiliate-matching-review__desk/, "Inspector must not revive the split desk");
assert.doesNotMatch(queue, /affiliate-matching-review__strip/, "Inspector must not use the mint decision strip");
assert.match(queue, /affiliate-matching-review__hint|reviewHint/, "Review hint must stay compact (title/tooltip)");
assert.doesNotMatch(queue, /affiliate-matching-kpis/, "v10 must drop the five flat KPI cards");
assert.doesNotMatch(
  queue,
  /table-wrap[\s\S]{0,200}?affiliateMatching\.title/,
  "v10 must not duplicate the Intelligence lane title in the results header",
);
assert.doesNotMatch(queue, /affiliate-matching-toolbar__meta|const metaChips/, "v12 toolbar must drop Eligible/Stale meta chips");
assert.match(queue, /affiliate-matching-toolbar__safety|affiliateMatching\.noAutoPlacement/, "v12 must keep safety as a compact control");
assert.match(queue, /affiliate-matching-empty|affiliateMatching\.emptyHint/, "Empty matching queue must have a dedicated empty state");
assert.match(queue, /MatchingToolbarGlyph|affiliate-matching-toolbar__glyph/, "Toolbar actions must use compact glyphs");
assert.match(queue, /affiliate-matching-spectrum/, "Matching page must show a status-mix spectrum chart");
assert.match(queue, /affiliate-matching-spectrum__donut/, "Spectrum must include a donut status mix");
assert.match(queue, /affiliate-matching-spectrum__plot|affiliate-matching-spectrum__bars/, "Spectrum must include filterable attention bars");
assert.match(queue, /overridden_count/, "Spectrum must consume overridden_count from queue KPIs");
assert.match(queue, /filter:\s*"OVERRIDDEN"/, "Queue signals must include Overridden as a filterable status");
assert.match(queue, /filter:\s*"REJECTED"/, "Queue signals must include Rejected as a filterable status");
const signalBarsBlock = queue.match(/const signalBars = \[[\s\S]*?\];/);
assert.ok(signalBarsBlock, "signalBars block must exist");
assert.doesNotMatch(signalBarsBlock[0], /key:\s*"stale"/, "Stale must not replace a decision-status bar in Queue Signals");
assert.match(v10, /--pl-iq-mint|--pl-iq-label-quiet|--pl-iq-label-strong/, "v10 CSS must use Intelligence tokens");
assert.match(v10, /affiliate-matching-toolbar/, "v10 CSS must style the toolbar");
assert.match(v10, /affiliate-matching-review/, "v10 CSS must style the review panel");
assert.match(spectrum, /affiliate-matching-spectrum__donut/, "v11 CSS must style the spectrum donut");
assert.match(spectrum, /--pl-iq-mint|--pl-iq-label-quiet|--pl-iq-label-strong/, "v11 spectrum CSS must use Intelligence tokens");
assert.match(v12, /grid-template-columns/, "v12 toolbar CSS must use a single-row grid");
assert.match(v12, /affiliate-matching-toolbar__safety/, "v12 CSS must style the compact safety control");
assert.match(v13, /affiliate-matching-reel|affiliate-fit-score|affiliate-matching-status/, "v13 CSS must densify reel/fit/status cells");
assert.match(v13, /--pl-iq-mint|--pl-iq-label-quiet|--pl-iq-label-strong/, "v13 table CSS must use Intelligence tokens");
assert.match(v14, /affiliate-matching-suggestions|affiliate-matching-review__fields/, "v14 CSS must densify suggestions and fields");
assert.match(v15, /affiliate-matching-review__desk/, "v15 CSS history may remain but is superseded");
assert.match(v16, /affiliate-matching-review__strip/, "v16 CSS history may remain but is superseded");
assert.match(v17, /affiliate-matching-review__inspector|affiliate-matching-suggestions__score/, "v17 CSS history may remain but is superseded");
assert.match(v18, /max-width:\s*none|width:\s*100%/, "v18 CSS history may remain but is superseded");
assert.match(v19, /max-width:\s*3[68]rem|max-width:\s*40rem/, "v19 CSS history may remain but is superseded");
assert.match(v20, /work-item-details-drawer|affiliate-matching-review\.is-v20/, "v20 CSS history may remain but is superseded");
assert.match(v21, /affiliate-matching-review__context|affiliate-matching-review__footer/, "v21 CSS history may remain but is superseded");
assert.match(v22, /flex:\s*1|min-height:\s*0/, "v22 CSS history may remain but is superseded");
assert.match(v23, /affiliate-matching-review__reel|affiliate-matching-review__facts|affiliate-matching-review__breakdown/, "v23 CSS history may remain but is superseded by v24");
assert.match(v24, /--pl-iq-fs-eyebrow:\s*0\.62rem/, "v24 must define eyebrow type step");
assert.match(v24, /--pl-iq-fs-body:\s*0\.84rem/, "v24 must define body type step");
assert.match(v24, /--pl-iq-fs-title:\s*1\.05rem/, "v24 must define title type step");
assert.match(v24, /--pl-iq-fs-score:\s*0\.88rem/, "v24 must define score type step");
assert.match(v24, /--pl-iq-mint|--pl-iq-label-quiet|--pl-iq-label-strong/, "v24 review CSS must use Intelligence tokens");
assert.match(en, /"emptyHint":/, "en.json must include affiliateMatching.emptyHint");
assert.match(vi, /"emptyHint":/, "vi.json must include affiliateMatching.emptyHint");
assert.match(en, /"spectrumStatusMix":/, "en.json must include affiliateMatching.spectrumStatusMix");
assert.match(vi, /"spectrumStatusMix":/, "vi.json must include affiliateMatching.spectrumStatusMix");
assert.match(en, /"reviewDecide":/, "en.json must include affiliateMatching.reviewDecide");
assert.match(vi, /"reviewDecide":/, "vi.json must include affiliateMatching.reviewDecide");
assert.match(en, /"reviewProductFacts":/, "en.json must include affiliateMatching.reviewProductFacts");
assert.match(vi, /"reviewProductFacts":/, "vi.json must include affiliateMatching.reviewProductFacts");
assert.match(en, /"reviewScoreBreakdown":/, "en.json must include affiliateMatching.reviewScoreBreakdown");
assert.match(vi, /"reviewScoreBreakdown":/, "vi.json must include affiliateMatching.reviewScoreBreakdown");
assert.match(en, /"reviewMatchMeta":/, "en.json must include affiliateMatching.reviewMatchMeta");
assert.match(vi, /"reviewMatchMeta":/, "vi.json must include affiliateMatching.reviewMatchMeta");

console.log("affiliate-matching-polish: PASS");
