/**
 * Ops Accounts — platform triage plus controlled Facebook Page onboarding.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const webSrc = resolve(testDir, "..");

const page = readFileSync(resolve(webSrc, "components/ops-console/OpsAccountsPage.tsx"), "utf8");
const canonicalRoute = readFileSync(resolve(webSrc, "app/publishing/accounts/page.tsx"), "utf8");
const css = readFileSync(resolve(webSrc, "app/globals.css"), "utf8");
const en = readFileSync(resolve(webSrc, "lib/i18n/en.json"), "utf8");
const vi = readFileSync(resolve(webSrc, "lib/i18n/vi.json"), "utf8");
const pkg = readFileSync(resolve(webSrc, "../package.json"), "utf8");

assert.match(page, /ops-accounts-page/, "Accounts page must use scoped ops-accounts-page shell");
assert.match(page, /OperatorStudioShell/, "Accounts must render in Operator Studio");
assert.doesNotMatch(page, /OpsConsoleShell/, "Accounts must not require the Ops Console shell");
assert.match(canonicalRoute, /OpsAccountsPage/, "Publishing must expose the canonical Accounts route");
assert.match(page, /ops-accounts-spectrum/, "Accounts page must render the readiness spectrum");
assert.match(page, /ops-accounts-spectrum__insights/, "Accounts page must render large operational insights");
assert.match(page, /ops-accounts-freshness|opsAccounts\.loadedAt/, "Accounts page must surface load freshness");
assert.match(page, /fetchAllPlatformAccounts/, "Accounts page must keep platform-accounts authority");
assert.match(page, /fetchPublishControlQueue/, "Accounts page must keep queue health authority for unhealthy KPI");
assert.match(page, /createPlatformAccount/, "Accounts page must support creating a Facebook Page account");
assert.match(page, /updatePlatformAccount/, "Accounts page must support editing a Facebook Page account");
assert.match(page, /checkFacebookAccountSetup/, "Accounts page must expose the fail-closed Page setup check");
assert.match(page, /fetchFacebookPublishSafetyStatus/, "Accounts page must load effective Page safety status");
assert.match(page, /startFacebookOAuth/, "Accounts page must start the server-controlled Meta OAuth flow");
assert.match(page, /completeFacebookOAuthCallback/, "Accounts page must complete OAuth after the Meta redirect");
assert.match(page, /connectFacebookOAuthPage/, "Accounts page must connect a discovered Page without receiving its token");
assert.match(page, /updateFacebookOAuthConfiguration/, "Accounts page must save Meta App configuration through the API");
assert.match(page, /type="password"/, "Meta App Secret must use a password input");
assert.match(page, /secretPreservePlaceholder/, "Saved Meta App Secret must be write-only and preserved when blank");
assert.doesNotMatch(page, /session\.pages\.length === 1/, "OAuth callback must not auto-consume the session after one Page");
assert.match(page, /selectedOAuthPageIds|connectSelectedPages/, "Accounts must support selecting multiple Pages from one OAuth session");
assert.match(page, /oauthCatalogPages|oauthSessionConnectedPageIds/, "Picker must retain safe Page metadata to show post-add status");
assert.match(page, /setSelectedOAuthPageIds\(\[\]\)/, "Discovered Pages must start unselected so the operator chooses explicitly");
assert.match(page, /oauthPageState|RECONNECT_REQUIRED|MISSING_PERMISSIONS|NEEDS_ATTENTION|ARCHIVED|STATUS_UNAVAILABLE/, "Page picker must classify existing, unknown and unsafe Page states");
assert.match(page, /processSelectedPages|selectedNewPageCount|selectedReconnectPageCount/, "Selected action must distinguish new Pages from reconnects");
assert.match(page, /fetchFacebookOAuthSession/, "Accounts must refresh authoritative remaining Pages after each batch");
assert.match(page, /type="checkbox"/, "Discovered Pages must use explicit multi-select controls");
assert.doesNotMatch(page, /platform-credential:\/\//, "Managed OAuth credential references must not be rendered in the Accounts UI");
assert.doesNotMatch(page, /registerExistingFacebookReel/, "Accounts must not own publication import");
assert.doesNotMatch(page, /preflightFacebookInsights|collectFacebookInsightsOnce/, "Accounts must not own publication Insights operations");
assert.match(page, /\/publishing\/publications/, "Accounts must link operators to the Publication Library");
assert.match(page, /ops-accounts-table-shell|<table className="ops-accounts-table"/, "Accounts page must render a traditional operational table");
assert.match(page, /<thead>|<tbody|scope="rowgroup"/, "Account table must preserve familiar column headers and readiness groups");
assert.match(page, /ops-accounts-table__performance|success_rate_percent/, "Account table must visualize seven-day performance");
assert.match(page, /ops-accounts-table__action|openEdit\(account\)/, "Every account row must expose its Setup action");
assert.match(page, /ops-accounts-table__action[\s\S]*kind="settings"/, "Account row actions must use an unambiguous settings icon");
assert.match(page, /aria-label=\{`\$\{t\("opsAccounts\.setup"\)\}/, "Icon-only Setup actions must retain an accessible label");
assert.match(page, /accountAvatarLabel|ops-accounts-table__avatar/, "Every account row must lead with a Facebook Page avatar");
assert.match(page, /accountAvatarUrl|facebook_page_picture_url|<img/, "Accounts must render a real Page picture when Meta provides one");
assert.doesNotMatch(page, /handleShelfWheel|handleShelfPointerDown|ops-accounts-shelves/, "Account roster must not retain the horizontal shelf interaction");
assert.match(page, /performance7d|attemptsFailed7d/, "Account roster must surface seven-day performance");
assert.match(page, /assignedScheduledCounts|queueWorkload/, "Account roster must surface assigned and scheduled workload");
assert.match(page, /next_publish_at|warmup_stage/, "Account roster must surface the next publish window and warm-up stage");
assert.match(page, /ops-accounts-chip/, "Accounts page must use soft status/hold chips");
assert.match(page, /readinessLanes|laneAttention/, "Accounts page must group attention accounts into a dedicated lane");
assert.match(page, /collapsedLanes|toggleReadinessLane|aria-expanded/, "Readiness groups must support accessible expand and collapse");
assert.match(page, /ops-accounts-toolbar|ops-accounts-actions/, "Triage links must sit in the compact toolbar");
assert.match(page, /ops-accounts-board__commands[\s\S]*ops-accounts-add-page[\s\S]*ops-accounts-actions/, "Add Page must sit with the account roster before secondary navigation");
assert.match(page, /\/publishing\/drafts/, "Accounts page must deep-link same-session publish drafts");
assert.doesNotMatch(page, /href="\/ops\//, "Accounts must not force an Ops Console login switch");
assert.match(page, /ops-accounts-setup|setupFootnote/, "Accounts must render the controlled setup wizard and authority note");
assert.match(page, /ops-accounts-tabs|role="tablist"/, "Accounts setup must use real gated tabs");
assert.match(page, /ops-accounts-setup__rail|ops-accounts-setup__workspace/, "Accounts setup must separate step navigation from its work area");
assert.match(page, /setupMethod|ops-accounts-method-switch|ops-accounts-manual-panel/, "Account onboarding must show only the selected OAuth or manual method");
assert.match(page, /<section aria-label=\{t\("opsAccounts\.manualFallbackTitle"\)\} className="ops-accounts-manual-panel">/, "Manual setup must retain an accessible section label");
assert.doesNotMatch(page, /<header><span><b>\{t\("opsAccounts\.manualFallbackTitle"\)\}/, "Manual setup must not repeat the selected method title inside the form");
assert.match(page, /className="ops-accounts-save-check primary"[\s\S]*opsAccounts\.saveAndCheck/, "Manual setup must present Save & check as the primary action");
assert.match(page, /ops-accounts-manual-validation|manualValidationMissing|manualValidationReady/, "Manual setup must show compact validation context beside Save & check");
assert.match(en, /"manualValidationReady"|"manualValidationMissing"/, "en.json must define manual setup validation status labels");
assert.match(vi, /"manualValidationReady"|"manualValidationMissing"/, "vi.json must define manual setup validation status labels");
assert.match(css, /ops-accounts-manual-panel \.ops-accounts-manual-fallback__body[\s\S]*grid-template-columns: minmax\(0, 1fr\)/, "Manual setup actions must use a full-width footer instead of a narrow side column");
assert.match(page, /ops-accounts-field-label/, "Meta configuration fields must use custom labeled controls");
assert.doesNotMatch(page, /kind="identity"|kind="key"|kind="link"|kind="code"/, "Form labels must remain icon-free");
assert.match(page, /activeSafety|eligible_for_publish/, "Accounts must display server safety authority");
assert.match(page, /ops-accounts-safety-dashboard|ops-accounts-safety-runway|ops-accounts-safety-controls/, "Publishing safety must use the control-room layout");
assert.match(page, /ops-accounts-safety-actions[\s\S]*ops-accounts-publication-link[\s\S]*opsAccounts\.saveSafety/, "Publishing safety actions must separate library navigation from safety commands");
assert.match(css, /Publishing Accounts v40|ops-accounts-safety-dashboard \.ops-accounts-safety-metrics[\s\S]*repeat\(6/, "Publishing safety must present a complete six-metric rail on desktop");
assert.match(page, /safetyStages|publishingRunway|stageCompleted|stageCurrent|stageUpcoming/, "Publishing safety must show the staged runway progression");
assert.match(css, /Publishing Accounts v41|ops-accounts-safety-command-grid[\s\S]*ops-accounts-safety-runway/, "Publishing safety must use the staged runway + guardrail composition");
assert.match(css, /Publishing Accounts v42|--safety-text-xs: 0\.625rem|--safety-text-value: 0\.875rem/, "Publishing safety must use a readable, project-aligned typography scale");
assert.match(css, /Publishing Accounts v43|ops-accounts-safety-runway__head > \.ops-accounts-chip::before|border-radius: 999px/, "Runway stage labels must use semantic status pills");
assert.match(css, /ops-accounts-safety-runway__head > \.ops-accounts-chip::before\s*\{[^}]*border: 0;[^}]*box-shadow: none;/, "Runway stage dot must remain solid and must not resemble the digit zero");
assert.match(page, /ops-accounts-consent(?: is-wide)?\$\{setupForm\.isOnHold \? " is-enabled"/, "Operator hold must expose its enabled visual state");
assert.match(css, /Publishing Accounts v44|input\[type="checkbox"\][\s\S]*min-height: 22px|ops-accounts-safety-actions > \.ops-accounts-publication-link/, "Operator hold and safety actions must use the compact control dock");
assert.match(css, /Publishing Accounts v45|ops-accounts-safety-controls[\s\S]*min-height: 46px|ops-accounts-safety-actions[\s\S]*min-height: 40px/, "Operator hold dock must keep the compact vertical rhythm");
assert.match(page, /ops-accounts-safety-control-deck[\s\S]*ops-accounts-safety-controls[\s\S]*ops-accounts-safety-actions/, "Operator hold and actions must share one compact control deck");
assert.match(css, /Publishing Accounts v46|grid-template-areas: "hold reason cooldown actions"/, "Operator hold ribbon must use intentional desktop placement");
assert.match(css, /Publishing Accounts v47|grid-template-areas: "hold reason" "hold cooldown" "actions actions"/, "Operator hold must use a balanced two-tier composition instead of one crowded row");
assert.match(css, /Publishing Accounts v48|column-gap: 16px|clear separation between hold card and field stack/, "Operator hold layout must keep a visible gap between the card and field stack");
assert.match(css, /Publishing Accounts v49|grid-template-areas: "hold reason" "cooldown actions"/, "Operator hold must use the balanced 2×2 composition");
assert.match(page, /ops-accounts-safety-control-deck|ops-accounts-safety-control-deck__state|ops-accounts-safety-control-deck__workspace/, "Operator hold must group state and reason/actions into a control deck");
assert.match(css, /Publishing Accounts v52|grid-template-columns: minmax\(270px, 0\.74fr\) minmax\(0, 1\.26fr\)/, "Operator hold must use the two-zone Safety Control Deck layout");
assert.match(css, /Publishing Accounts v53|grid-template-columns: minmax\(250px, 0\.62fr\) minmax\(0, 1\.38fr\)/, "Operator hold must use the Safety Override Capsule layout");
assert.match(css, /Publishing Accounts v54|grid-template-areas: "hold cooldown reason" "actions actions actions"/, "Operator hold must align cooldown and reason in one command row with a single action rail");
assert.match(css, /Publishing Accounts v55|border-color: #4d9a7a;[\s\S]*box-shadow: 0 0 0 3px rgba\(55, 143, 109, 0\.12\)/, "Safety fields must use the project-aligned teal focus state");
assert.match(page, /ops-accounts-operations-card|ops-accounts-operations-controls|ops-accounts-operations-notes/, "Account operations must use the compact control-surface layout");
assert.match(page, /ops-accounts-operations-actions[\s\S]*className="primary"[\s\S]*opsAccounts\.saveAndCheck/, "Account operations must present the save action in the polished primary footer");
assert.match(page, /ops-accounts-operations-deck|ops-accounts-operations-avatar|activeAccountAvatarUrl/, "Account operations must lead with the Facebook profile command deck");
assert.match(page, /operationsSaveHint/, "Account operations must explain the save/check sequence beside the CTA");
assert.match(css, /Publishing Accounts v38|ops-accounts-operations-controls[\s\S]*grid-template-columns: minmax\(0, 1fr\) 170px/, "Account operations styles must keep status wide and priority compact");
assert.match(css, /Publishing Accounts v39|ops-accounts-operations-deck[\s\S]*grid-template-columns: minmax\(310px, 0\.82fr\)/, "Account operations must use the profile command deck layout");
assert.match(page, /warmup_stage|confirmed_connector_publishes|next_stage_min_successes/, "Accounts must explain staged warm-up progression");
assert.match(page, /holdReason|cooldownUntil|allowedNiches|routingNotes/, "Accounts must expose hold, cooldown and routing fields");
assert.match(page, /managedAccount|oauthManagedFields/, "OAuth-managed identity fields must be read-only");
assert.match(page, /ops-accounts-managed-identity/, "OAuth-managed identity must render as a compact summary");
assert.match(page, /ops-accounts-manual-fallback/, "Manual Page identity must stay behind an explicit fallback disclosure");
assert.match(page, /blockingGroupLabel|warningGroupLabel|passedGroupLabel/, "Setup checks must distinguish blockers, warnings and passed checks");
assert.match(page, /AccountIcon|ops-accounts-icon-button/, "Accounts actions must use purposeful inline icons");
assert.doesNotMatch(page, /health-overview-grid/, "Accounts page must leave shared health-overview-grid");
assert.doesNotMatch(page, /health-table/, "Accounts page must not use health-table");
assert.doesNotMatch(page, /<OpsMetricCard/, "Accounts page must not use shared OpsMetricCard");
assert.doesNotMatch(page, /<OpsPanel/, "Accounts page must not use shared OpsPanel");
assert.doesNotMatch(page, /<StatusBadge/, "Accounts page must not use StatusBadge");

assert.match(css, /\.ops-accounts-page/, "CSS must define Accounts page shell");
assert.match(css, /\.ops-accounts-spectrum/, "CSS must define the readiness spectrum");
assert.match(css, /\.ops-accounts-table-shell|\.ops-accounts-table__row/, "CSS must define the operational table surface and rows");
assert.match(css, /\.ops-accounts-table__performance|\.ops-accounts-table__window/, "Table must visualize performance and publish-window state");
assert.match(css, /\.ops-accounts-meta-config__body \.ops-accounts-form-grid[^}]*grid-template-columns:\s*repeat\(3/, "Meta configuration must use a compact three-column desktop grid");
assert.match(css, /\.ops-accounts-tabs[^}]*grid-template-columns:\s*repeat\(2/, "Account setup must present its two steps as a balanced segmented control");
assert.match(css, /\.ops-accounts-setup[^}]*grid-template-columns:\s*minmax\(260px/, "Desktop onboarding must use a compact header-and-step layout");
assert.match(css, /\.ops-accounts-oauth:has\(\.ops-accounts-meta-config\[open\]\)/, "Expanded Meta configuration must progressively move into a full-width work area");
assert.match(css, /\.ops-accounts-oauth__actions \.async-button\.primary[^}]*#1877f2/, "Facebook OAuth must use the recognizable Meta action color");
assert.match(css, /button\[aria-expanded="false"\][^}]*chevron/, "Collapsed readiness groups must rotate their chevron indicator");
assert.match(css, /\.ops-accounts-board__head h2[^}]*font-size:\s*0\.9375rem/, "Accounts roster heading must remain readable at 15px");
assert.match(css, /\.ops-accounts-board__head p[^}]*font-size:\s*0\.75rem/, "Accounts roster description must remain readable at 12px");
assert.match(css, /\.ops-accounts-board__head > \.ops-accounts-board__commands[^}]*display:\s*flex/, "Desktop roster actions must remain on one horizontal row");
assert.match(css, /\.ops-accounts-table__avatar[^}]*border-radius:\s*50%/, "Facebook Page identity must use a circular avatar");
assert.match(css, /--ops-accounts-axis:\s*0\.6875rem|--ops-accounts-data:\s*0\.8125rem/, "Accounts typography must use the project's axis/meta/data scale");
assert.match(css, /position:\s*sticky/, "Wide account tables must retain sticky identity/action context");
assert.match(css, /\.ops-accounts-chip\s*\{[^}]*font-weight:\s*400/, "Accounts chips must not use bold weight");
assert.match(css, /\.ops-accounts-attention/, "CSS must define attention list");
assert.match(css, /\.ops-accounts-footnote/, "CSS must define compact footnote");
assert.match(css, /\.ops-accounts-attention-strip/, "CSS must define the compact attention strip");
assert.match(css, /\.ops-accounts-setup/, "CSS must define the Facebook setup surface");
assert.match(css, /\.ops-accounts-checks/, "CSS must define setup and preflight check lists");
assert.match(css, /\.ops-accounts-publication-link/, "CSS must style the Publication Library handoff");
assert.match(css, /\.ops-accounts-oauth/, "CSS must define the automatic Facebook connection surface");
assert.match(css, /\.ops-accounts-meta-config/, "CSS must define the secure Meta App configuration surface");
assert.match(css, /\.ops-accounts-page-picker/, "CSS must define the multi-Page picker");
assert.match(css, /\.ops-accounts-page-picker__list/, "CSS must style multi-select Page cards");
assert.match(css, /state-new|state-connected|state-reconnect_required|state-missing_permissions|state-needs_attention|state-archived|state-status_unavailable/, "CSS must give every Page state a distinct visual treatment");
assert.match(css, /\.ops-accounts-managed-identity/, "CSS must style the managed identity summary");
assert.match(css, /\.ops-accounts-manual-fallback/, "CSS must keep manual setup secondary");
assert.match(css, /\.ops-accounts-tabs/, "CSS must define setup tabs");
assert.match(css, /\.ops-accounts-setup__rail[^}]*background:\s*#fff/, "Setup navigation must use a quiet light toolbar instead of a heavy sidebar");
assert.match(css, /\.ops-accounts-field-label[^}]*display:\s*block/, "Onboarding fields must use clean icon-free labels");
assert.match(css, /\.ops-accounts-manual-fallback__body > \.ops-accounts-form-grid[^}]*repeat\(4/, "Manual fallback must use a compact four-column desktop form");
assert.match(css, /\.ops-accounts-method-switch[^}]*repeat\(2/, "Connection methods must use a balanced two-option selector");
assert.match(css, /\.ops-accounts-setup__rail[^}]*minmax\(420px, 560px\)[^}]*auto/, "Onboarding header must place title, progress and Close in a balanced row");
assert.match(css, /\.ops-accounts-setup__head > button[^}]*grid-column:\s*3/, "Close must remain the rightmost desktop action");
assert.match(css, /\.ops-accounts-setup__head > button \.ops-accounts-icon[^}]*border-radius:\s*50%/, "Close must use a distinct circular icon treatment");
assert.match(css, /\.ops-accounts-setup__head > button[^}]*height:\s*40px/, "Close must align with the onboarding stepper height");
assert.match(css, /\.ops-accounts-setup__workspace > \.ops-accounts-oauth[^}]*grid-template-columns:\s*minmax\(0, 1fr\) auto auto/, "OAuth command row must size status and action to their content");
assert.match(css, /\.ops-accounts-meta-config > summary[^}]*grid-template-columns:\s*minmax\(0, 1fr\) auto auto/, "Meta configuration summary must keep status and chevron together on the right");
assert.match(css, /\.ops-accounts-meta-config__body \.ops-accounts-form-grid[^}]*140px[^}]*minmax\(360px/, "Meta form must reserve a compact version column and a wider secret column");
assert.match(page, /is-app-id|is-app-secret|is-redirect|is-version/, "Meta fields must use stable named layout hooks");
assert.match(page, /ops-accounts-meta-config__footer|ops-accounts-meta-scopes/, "Permissions and Save must share a compact footer composition");
assert.match(page, /ops-accounts-manual-groups|manualIdentityGroup|manualDefaultsGroup/, "Manual setup must use grouped identity, credential and defaults panels");
assert.match(css, /grid-template-areas:\s*"app version secret" "redirect redirect redirect"/, "Meta form fields must use non-overlapping named grid areas");
assert.match(css, /\.ops-accounts-meta-config__footer[^}]*grid-template-columns:\s*minmax\(0, 1fr\) auto/, "Permissions footer must keep Save beside the permission chips");
assert.match(css, /\.ops-accounts-manual-groups[^}]*grid-template-columns:\s*minmax\(0, 1fr\)/, "Manual setup must use a responsive grouped bento layout");
assert.match(page, /ops-accounts-disclosure-toggle[\s\S]*kind="chevron"/, "Meta configuration must render an explicit SVG disclosure indicator");
assert.match(css, /\.ops-accounts-meta-config\[open\] \.ops-accounts-disclosure-toggle[^}]*rotate\(180deg\)/, "Disclosure indicator must reflect the expanded state");
assert.match(css, /\.ops-accounts-setup__workspace > \.ops-accounts-oauth[^}]*grid-template-columns:\s*minmax\(0, 1fr\) auto/, "OAuth setup must use a compact title-and-action row");
assert.match(css, /\.ops-accounts-safety-banner/, "CSS must define the safety status summary");
assert.match(css, /\.ops-accounts-icon-button|\.ops-accounts-board \.ops-accounts-actions/, "CSS must style icon actions and command links");

assert.match(en, /"loadedAt"|"attention"|"editsInPublishControl"/, "en.json must define Accounts redesign labels");
assert.match(en, /"tableViewHint"|"accountCount"/, "en.json must define the grouped table labels");
assert.match(en, /"yes"|"no"/, "en.json must define hold yes/no");
assert.match(vi, /"loadedAt"|"attention"|"editsInPublishControl"/, "vi.json must define Accounts redesign labels");
assert.match(vi, /"tableViewHint"|"accountCount"/, "vi.json must define the grouped table labels");
assert.match(vi, /"yes"|"no"/, "vi.json must define hold yes/no");
assert.match(en, /"addFacebookPage"|"collectInsightsOnce"/, "en.json must define Facebook onboarding labels");
assert.match(vi, /"addFacebookPage"|"collectInsightsOnce"/, "vi.json must define Facebook onboarding labels");
assert.match(en, /"connectFacebook"|"oauthSetupRequired"/, "en.json must define Facebook OAuth labels");
assert.match(vi, /"connectFacebook"|"oauthSetupRequired"/, "vi.json must define Facebook OAuth labels");
assert.match(en, /"saveMetaConfiguration"|"secretNeverReturned"/, "en.json must define secure Meta configuration labels");
assert.match(vi, /"saveMetaConfiguration"|"secretNeverReturned"/, "vi.json must define secure Meta configuration labels");
assert.match(en, /"operationsSaveHint"/, "en.json must define the Account operations save sequence hint");
assert.match(vi, /"operationsSaveHint"/, "vi.json must define the Account operations save sequence hint");
assert.match(en, /"publishingRunway"|"stageCompleted"/, "en.json must define runway labels");
assert.match(vi, /"publishingRunway"|"stageCompleted"/, "vi.json must define runway labels");
assert.match(en, /"addSelectedPages"|"manualFallbackTitle"/, "en.json must define multi-Page and fallback labels");
assert.match(vi, /"addSelectedPages"|"manualFallbackTitle"/, "vi.json must define multi-Page and fallback labels");

assert.match(pkg, /ops-accounts-ui\.test\.ts/, "package.json must run ops-accounts-ui test");

console.log("ops-accounts-ui tests passed");
