/**
 * Ops Health V4 — one diagnostic canvas instead of a metric-card collection.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const webSrc = resolve(testDir, "..");

const page = readFileSync(resolve(webSrc, "components/ops-console/OpsHealthPage.tsx"), "utf8");
const css = readFileSync(resolve(webSrc, "app/globals.css"), "utf8");
const en = readFileSync(resolve(webSrc, "lib/i18n/en.json"), "utf8");
const vi = readFileSync(resolve(webSrc, "lib/i18n/vi.json"), "utf8");

assert.match(page, /ops-health-page is-dense|ops-health-page/, "Health page must use scoped ops-health-page shell");
assert.match(page, /HealthDecisionCanvas/, "Health page must render one operational decision canvas");
assert.match(page, /ops-health-command/, "Health page must lead with an overall incident-aware command band");
assert.match(page, /DependencyTopology/, "Health page must expose dependency readiness as a layered topology");
assert.match(page, /ops-health-v2-topology__spine/, "Dependency readiness must follow the system execution spine");
assert.match(page, /ops-health-v3-topology-map/, "Dependencies must use the balanced 2x2 system map");
assert.doesNotMatch(page, /<table className="ops-health-dependency-table"/, "Dependency readiness must not remain a dense table");
assert.match(page, /ops-health-incidents/, "Health page must show only actionable non-zero incidents");
assert.match(page, /sortedIncidents\.slice\(0, 5\)/, "Health triage must cap the severity-ranked stream and use progressive disclosure");
assert.match(page, /ops-health-v3-incidents__more/, "Capped incidents must disclose the remaining signal count");
assert.match(page, /visibleIncidentGroups/, "Incident ledger must group visible signals by severity");
assert.match(page, /ops-health-v7-ledger__number/, "Incident counts must become the visual anchor of each ledger row");
assert.match(page, /topImpactIncident/, "Incident ledger must identify the largest visible impact without inventing a metric");
assert.doesNotMatch(page, /ops-health-v6-incident-magnitude|incident\.count \/ incidentPeak/, "Incident ledger must not retain the rejected micro-bar treatment");
assert.match(page, /running_without_lock|active_worker_count/, "Worker health must use lock authority instead of running count alone");
assert.match(page, /oldest_queued_at/, "Health page must surface oldest queue age");
assert.match(page, /ops-health-v4-incident-focus/, "Health canvas must prioritize incidents in one focus region");
assert.match(page, /ops-health-v4-flow/, "Queue, observability, and workers must form a connected execution path");
assert.match(page, /ops-health-v4-foundation/, "Storage and integrity must share a foundation strip");
assert.doesNotMatch(page, /HealthKpiCard|ops-health-v3-kpi-bento/, "Health decisions must not fall back to cards or bento tiles");
assert.match(page, /ops-health-panels is-dense/, "Health panels must use dense two-column layout");
assert.match(page, /ops-health-panel__head/, "Panels must expose a spaced heading region");
assert.match(page, /PipelineVolumeChart/, "Workload must replace the dense job table with a volume chart");
assert.match(page, /OutputCompositionChart/, "Render and publish outcomes must use proportional composition rails");
assert.match(page, /AssetReusePlot/, "Asset reuse must use a paired current-versus-historical plot");
assert.match(page, /render_counts_by_status/, "Output composition must read render_counts_by_status");
assert.match(page, /publish_draft_counts_by_status/, "Output composition must read publish_draft_counts_by_status");
assert.doesNotMatch(page, /<JobMatrixTable|<StatusChips|<MeterList|<AssetReuseList/, "Visual canvas must not render the rejected table, chip, or generic meter treatments");
assert.match(page, /opsHealth\.badgeHealthy|badgeHealthy/, "Health badges must use i18n labels");
assert.match(page, /generated_at/, "Health page must surface metrics freshness");
assert.match(page, /ops-health-freshness|opsHealth\.metricsGenerated/, "Health page must render metrics generated timestamp");
assert.match(page, /common_failure_categories/, "Health page must surface common failure categories");
assert.match(page, /ops-health-failures|opsHealth\.commonFailures/, "Health page must render failure categories");
assert.match(page, /douyin_fetch_health/, "Health page must surface Douyin fetch health");
assert.match(page, /ops-health-fetch|opsHealth\.fetchHealth/, "Health page must render fetch health");
assert.match(page, /open_risk_counts_by_severity/, "Health page must surface risk severity breakdown");
assert.match(page, /ops-health-risk|opsHealth\.riskBySeverity/, "Health page must render risk severity");
assert.match(page, /average_processing_seconds_per_source_video|job_failure_rate_percent_by_type/, "Health page must surface processing or failure-rate signal");
assert.match(page, /opsHealth\.workload|opsHealth\.signals/, "Dense layout must merge into workload/signals panels");
assert.doesNotMatch(page, /opsHealth\.failureRates(?!Short)/, "Dense layout must fold failure rates into signals (no standalone panel)");
assert.doesNotMatch(page, /health-overview-grid/, "Health page must leave shared health-overview-grid");
assert.doesNotMatch(page, /<OpsMetricCard/, "Health page must not use shared OpsMetricCard");
assert.doesNotMatch(page, /<OpsPanel/, "Health page must not use shared OpsPanel");
assert.match(page, /fetchOperationalMetrics/, "Health page must keep metrics authority");
assert.match(page, /fetchPublishHealthDashboard/, "Health page must keep publish health authority");
assert.match(page, /fetchOpsHomeSummary/, "Health page must use canonical dependency, admission, and hidden-risk evidence");
assert.match(page, /homeSummary\.dependencies/, "Health dependencies must come from backend probes instead of browser inference");
assert.match(page, /homeSummary\?\.hidden_risks/, "Health must expose the hidden-risk ledger");
assert.match(page, /admission_verdict|homeSummary\?\.admission_verdict/, "Health must surface the backend admission verdict");
assert.match(page, /trueRetryClaims/, "Health must show retry claims rather than total worker claims");
assert.match(page, /by_day|publishHealth\.by_day/, "Health page must chart publish by_day authority");
assert.match(page, /PublishColumnChart|ops-health-v10-columns/, "Publish activity must render as a compact stacked daily column chart");
assert.match(page, /axisCeiling = maxAttempts <= 1 \? 2/, "Sparse daily activity must retain honest vertical headroom");
assert.match(page, /day\.needs_reconciliation/, "Daily columns must stack reconciliation alongside success and failure");
assert.match(page, /totalAttempts === 0/, "A zero-activity publish window must render an explicit empty state");
assert.doesNotMatch(page, /<PublishWeekChart|<PublishingPulse/, "Health page must not retain the oversized or pulse-based publish charts");
assert.match(page, /ops-health-meters|ops-health-meter/, "Health page must render proportion meters");
assert.match(page, /ops-health-queue-mix|queue_backlog/, "Health page must visualize queue mix from backlog");
assert.match(page, /success_rate_percent|opsHealth\.publishSuccessRate/, "Health page must surface publish overview success rate");
assert.match(page, /overview\.|publishHealth\.overview/, "Health page must read publishHealth.overview");
assert.match(page, /ops-health-v9-coverage|unobservedDependencies/, "Observation gaps must render as a compact coverage rail");
assert.doesNotMatch(page, /Observation boundary:/, "Coverage must not remain a detached prose paragraph");
assert.match(page, /href=.*\/ops\/risk|\/ops\/risk/, "Health page must deep-link to risk");
assert.match(page, /href=.*\/ops\/jobs|\/ops\/jobs\?status=/, "Health page must deep-link to jobs with status");
assert.match(page, /\/ops\/publish-health/, "Health page must deep-link to publish health");
assert.match(page, /ops-health-actions|opsHealth\.openJobs|opsHealth\.openRisk/, "Health page must render triage action links");
assert.match(page, /kind="play"[\s\S]*kind="details"[\s\S]*kind="retry"[\s\S]*kind="recheck"[\s\S]*kind="open"/, "Every Health triage chip must use a semantically distinct action icon");
assert.match(page, /asset_reuse_by_type/, "Health page must surface asset reuse rows");
assert.match(page, /ops-health-v8-assets|current_count|historical_count/, "Health page must visualize current and historical asset reuse");
assert.match(page, /by_account/, "Health page must surface fetch health by_account");
assert.match(page, /fetchAccounts\.length > 1/, "Single unknown-account rows must not consume visual canvas space");
assert.match(page, /job_counts_by_type_status/, "Health page must surface job type/status matrix");
assert.match(page, /ops-health-v8-pipeline|opsHealth\.pipelineVolume/, "Health page must render job volume as a pipeline chart");
assert.match(page, /FetchSignalVisual|ops-health-v8-fetch-visual/, "Fetch health must render as a segmented radial signal");
assert.match(page, /SignalPareto|ops-health-v8-pareto/, "Blocked reasons must render as a ranked Pareto chart");
assert.match(page, /FailureRateVisual|ops-health-v8-assurance/, "Zero failure rates must collapse into one assurance signal");

assert.match(css, /\.ops-health-page/, "CSS must define Health page shell");
assert.match(css, /\.ops-health-page\.is-dense|\.ops-health-panels\.is-dense/, "CSS must define dense Health layout");
assert.match(css, /\.ops-health-v4-decision-canvas/, "CSS must define the unified Health decision canvas");
assert.match(css, /\.ops-health-v8-canvas/, "CSS must define the operational visual canvas");
assert.match(css, /\.ops-health-freshness/, "CSS must define metrics freshness strip");
assert.match(css, /\.ops-health-v8-headline-stats/, "CSS must define integrated workload headline figures");
assert.match(css, /\.ops-health-failures/, "CSS must define failure categories list");
assert.match(css, /\.ops-health-fetch/, "CSS must define fetch health layout");
assert.match(css, /\.ops-health-v10-columns__plot/, "CSS must define the compact seven-day column plot");
assert.match(css, /\.ops-health-v10-columns__bar[\s\S]*flex-direction:\s*column-reverse/, "CSS must stack daily publication outcomes vertically");
assert.match(css, /\.ops-health-v10-columns__grid/, "CSS must define a readable axis grid without oversized empty space");
assert.match(css, /\.ops-health-v9-coverage/, "CSS must define the observation coverage rail");
assert.match(css, /\.ops-health-v8-pipeline__row/, "CSS must define pipeline volume bars");
assert.match(css, /\.ops-health-v8-outcomes__bar/, "CSS must define output composition rails");
assert.match(css, /\.ops-health-actions/, "CSS must define triage action links");
assert.match(css, /\.ops-health-v8-assets__row/, "CSS must define paired asset reuse plots");
assert.match(css, /\.ops-health-v8-fetch-visual__ring/, "CSS must define fetch-health radial visualization");
assert.match(css, /\.ops-health-v8-pareto__row/, "CSS must define Pareto bars for ranked signal causes");
assert.match(css, /\.ops-health-v8-assurance/, "CSS must define the compact zero-failure assurance strip");
assert.match(css, /\.ops-health-v2-command/, "CSS must define the diagnostic command chamber");
assert.match(css, /Ops Health V4[\s\S]*\.ops-health-v4-decision-canvas[\s\S]*grid-template-columns/, "Health decisions must use a split diagnostic canvas");
assert.match(css, /\.ops-health-v4-flow[\s\S]*repeat\(3/, "Execution evidence must render as a three-stage connected path");
assert.match(css, /\.ops-health-v4-foundation[\s\S]*1\.35fr/, "Foundation capacity and integrity must use a deliberate split strip");
assert.match(css, /\.ops-health-v2-action__icon/, "CSS must size and align triage action icons");
assert.match(css, /\.ops-health-v2-topology/, "CSS must define the layered dependency topology");
assert.match(css, /\.ops-health-v3-topology-map \.ops-health-v2-topology__spine[\s\S]*repeat\(2/, "Desktop dependency groups must form a balanced 2x2 system map");
assert.match(css, /\.ops-health-v3-incidents \.ops-health-incident-list[\s\S]*max-height:\s*none[\s\S]*overflow:\s*visible/, "Triage stream must not use an internal scrollbar");
assert.match(css, /\.ops-health-v7-ledger__group/, "CSS must define severity-grouped impact ledger sections");
assert.match(css, /\.ops-health-v7-ledger__number[\s\S]*font-variant-numeric:\s*tabular-nums/, "CSS must define legible tabular number wells");
assert.match(css, /\.ops-health-v7-ledger__row/, "CSS must integrate incident values and descriptions in one ledger row");
assert.doesNotMatch(css, /\.ops-health-v6-incident-magnitude|\.ops-health-v6-incidents__summary/, "CSS must remove the rejected magnitude-bar presentation");
assert.match(css, /\.ops-health-v2-risk-ledger/, "CSS must define the hidden-risk assurance ledger");
assert.match(css, /@media \(max-width: 760px\)[\s\S]*ops-health-v4-decision-canvas[\s\S]*grid-template-columns:\s*1fr/, "Health decision canvas must linearize on mobile");

assert.match(en, /"badgeHealthy"/, "en.json must define badgeHealthy");
assert.match(en, /"metricsGenerated"/, "en.json must define metricsGenerated");
assert.match(en, /"commonFailures"/, "en.json must define commonFailures");
assert.match(en, /"fetchHealth"/, "en.json must define fetchHealth");
assert.match(en, /"riskBySeverity"/, "en.json must define riskBySeverity");
assert.match(en, /"workload"/, "en.json must define workload");
assert.match(en, /"signals"/, "en.json must define signals");
assert.match(en, /"publishWeek"|"publishTrend"/, "en.json must define publish week chart label");
assert.match(en, /"publishSuccessRate"/, "en.json must define publishSuccessRate");
assert.match(en, /"queueMix"/, "en.json must define queueMix");
assert.match(en, /"openRisk"|"openJobs"/, "en.json must define triage link labels");
assert.match(en, /"assetReuse"|"assetsShort"/, "en.json must define asset reuse label");
assert.match(en, /"fetchByAccount"/, "en.json must define fetchByAccount");
assert.match(en, /"jobMatrix"/, "en.json must define jobMatrix");
assert.match(en, /"affectedRecords"/, "en.json must label affected incident records");
assert.match(en, /"highestImpact"/, "en.json must label the highest-impact incident");
assert.match(en, /"pipelineVolume"/, "en.json must label the workload volume chart");
assert.match(en, /"failureRateClear"/, "en.json must label the consolidated zero-failure state");
assert.match(en, /"publishingPulse"/, "en.json must label the adaptive publishing pulse");
assert.match(en, /"coverage"/, "en.json must label the observation coverage rail");
assert.match(en, /"publishReconciliation"/, "en.json must label daily reconciliation segments");
assert.match(vi, /"badgeHealthy"/, "vi.json must define badgeHealthy");
assert.match(vi, /"metricsGenerated"/, "vi.json must define metricsGenerated");
assert.match(vi, /"workload"/, "vi.json must define workload");
assert.match(vi, /"signals"/, "vi.json must define signals");
assert.match(vi, /"publishWeek"|"publishTrend"/, "vi.json must define publish week chart label");
assert.match(vi, /"publishSuccessRate"/, "vi.json must define publishSuccessRate");
assert.match(vi, /"queueMix"/, "vi.json must define queueMix");
assert.match(vi, /"openRisk"|"openJobs"/, "vi.json must define triage link labels");
assert.match(vi, /"assetReuse"|"assetsShort"/, "vi.json must define asset reuse label");
assert.match(vi, /"fetchByAccount"/, "vi.json must define fetchByAccount");
assert.match(vi, /"jobMatrix"/, "vi.json must define jobMatrix");
assert.match(vi, /"affectedRecords"/, "vi.json must label affected incident records");
assert.match(vi, /"highestImpact"/, "vi.json must label the highest-impact incident");
assert.match(vi, /"pipelineVolume"/, "vi.json must label the workload volume chart");
assert.match(vi, /"failureRateClear"/, "vi.json must label the consolidated zero-failure state");
assert.match(vi, /"publishingPulse"/, "vi.json must label the adaptive publishing pulse");
assert.match(vi, /"coverage"/, "vi.json must label the observation coverage rail");
assert.match(vi, /"publishReconciliation"/, "vi.json must label daily reconciliation segments");

console.log("ops-health-ui tests passed");
