/** Publication Library — discovery, import, draft linking and read-only Insights boundaries. */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const webSrc = resolve(testDir, "..");
const page = readFileSync(resolve(webSrc, "components/operator-routes/PublicationLibraryPage.tsx"), "utf8");
const trackingMonitor = readFileSync(resolve(webSrc, "components/operator-routes/PublicationTrackingMonitor.tsx"), "utf8");
const classificationPanel = readFileSync(resolve(webSrc, "components/operator-routes/PublicationClassificationPanel.tsx"), "utf8");
const classificationQueue = readFileSync(resolve(webSrc, "components/operator-routes/ContentClassificationQueue.tsx"), "utf8");
const taxonomyManager = readFileSync(resolve(webSrc, "components/operator-routes/ContentTaxonomyManager.tsx"), "utf8");
const contentAiConfiguration = readFileSync(resolve(webSrc, "components/operator-routes/ContentAiConfiguration.tsx"), "utf8");
const classificationPresentation = readFileSync(resolve(webSrc, "lib/contentClassificationPresentation.ts"), "utf8");
const contentIntelligenceSettingsPage = readFileSync(resolve(webSrc, "components/operator-routes/ContentIntelligenceSettingsPage.tsx"), "utf8");
const contentIntelligenceSettingsRoute = readFileSync(resolve(webSrc, "app/publishing/settings/content-intelligence/page.tsx"), "utf8");
const affiliateCatalogPage = readFileSync(resolve(webSrc, "components/operator-routes/AffiliateCatalogPage.tsx"), "utf8");
const publicHttpsUrl = readFileSync(resolve(webSrc, "lib/publicHttpsUrl.ts"), "utf8");
const affiliateMatchingQueue = readFileSync(resolve(webSrc, "components/operator-routes/AffiliateProductMatchingQueue.tsx"), "utf8");
const opportunityRanking = readFileSync(resolve(webSrc, "components/operator-routes/AffiliateOpportunityRanking.tsx"), "utf8");
const affiliateCommentPanel = readFileSync(resolve(webSrc, "components/operator-routes/AffiliateCommentPlacementPanel.tsx"), "utf8");
const affiliateCatalogCsv = readFileSync(resolve(webSrc, "lib/affiliateCatalogCsv.ts"), "utf8");
const affiliateImagePresentation = readFileSync(resolve(webSrc, "lib/affiliateImagePresentation.ts"), "utf8");
const affiliateCatalogSettingsRoute = readFileSync(resolve(webSrc, "app/publishing/settings/affiliate-catalog/page.tsx"), "utf8");
const affiliateCommentTemplatesPage = readFileSync(resolve(webSrc, "components/operator-routes/AffiliateCommentTemplatesSettingsPage.tsx"), "utf8");
const affiliateCommentTemplatesRoute = readFileSync(resolve(webSrc, "app/publishing/settings/affiliate-comments/page.tsx"), "utf8");
const route = readFileSync(resolve(webSrc, "app/publishing/publications/page.tsx"), "utf8");
const accountsPage = readFileSync(resolve(webSrc, "components/ops-console/OpsAccountsPage.tsx"), "utf8");
const api = readFileSync(resolve(webSrc, "lib/api.ts"), "utf8");
const nav = readFileSync(resolve(webSrc, "lib/navigationConfig.ts"), "utf8");
const css = readFileSync(resolve(webSrc, "app/globals.css"), "utf8");
const en = readFileSync(resolve(webSrc, "lib/i18n/en.json"), "utf8");
const vi = readFileSync(resolve(webSrc, "lib/i18n/vi.json"), "utf8");

assert.match(route, /PublicationLibraryPage/, "The canonical route must render Publication Library");
assert.match(route, /account_id/, "The canonical route must pass Page context into Publication Library");
assert.match(accountsPage, /publicationLibraryHref\(activeAccount\?\.id\)/, "Accounts must open the Library in the active Page context");
assert.match(page, /initialAccountId/, "Publication Library must accept an initial Page context");
assert.match(page, /platformAccountId: resolvedScope === "PAGE" \? resolvedAccountId : undefined/, "Current Page scope must filter the publication API request");
assert.match(page, /changePublicationScope/, "Library must expose explicit Current Page and All Pages scopes");
assert.match(page, /publication-library-studio[\s\S]*publication-library-page-bar[\s\S]*publication-library-tools[\s\S]*publication-library-desk/, "Publications view must use the Desk composition: command row, tools row, and desk body");
assert.match(page, /publication-library-tools is-v31|publication-library-tools[\s\S]*is-v31/, "Library tools must use the Lean Desk tools strip");
assert.match(page, /publication-library-filter-chips[\s\S]*setPublicationFilter/, "Library must expose filter chips that drive the roster filter instead of a KPI card strip");
assert.doesNotMatch(page, /publication-library-tools__meta[\s\S]*showingCount|showingCount[\s\S]*publication-library-tools__meta/, "Lean Desk must not show a redundant Showing X of Y meta line on the tools strip");
assert.doesNotMatch(page, /publication-library-worklist-metrics/, "Lean Desk worklist rows must not show Views metrics columns; metrics stay in the focus inspector");
assert.match(page, /publication-library-worklist-status[\s\S]*linkedState[\s\S]*trackedState|worklist-status[\s\S]*is-linked[\s\S]*is-tracked|linkedState[\s\S]*trackedState/, "Every publication worklist row must expose draft-link and tracking state");
assert.match(page, /publication-library-empty-inspector[\s\S]*selectPublication[\s\S]*PublicationLibraryIcon|empty-inspector__mark/, "Focus empty state must use a quiet marked empty treatment");
assert.match(css, /Publication Library v31[\s\S]*\.publication-library-tools\.is-v31[\s\S]*\.publication-library-worklist-status/, "Lean Desk must style the compact tools strip and status chips");
assert.doesNotMatch(page, /publication-library-kpi-strip/, "KPI strip cards must not remain the primary Library chrome");
assert.match(page, /publicationAccountAvatarUrl[\s\S]*publication-library-page-avatar[\s\S]*publication-library-page-bar/, "Page bar must combine Facebook identity, sync controls, and freshness");
assert.match(page, /publication-library-page-bar is-v30|publication-library-page-bar__compact/, "Page command chrome must use the Calm Compact composition");
assert.match(page, /publication-library-page-bar__name-row[\s\S]*picker-caret[\s\S]*publication-library-page-sync-state/, "Page picker must keep the name and caret on one row with a quiet status line below");
assert.match(page, /publication-library-page-bar__compact[\s\S]*publication-library-page-bar__cluster[\s\S]*publication-library-scope-tabs[\s\S]*kind="page"[\s\S]*kind="pages"[\s\S]*publication-library-page-bar__sync/, "Compact bar must keep scope chips and Sync in one action cluster");
assert.doesNotMatch(page, /publication-library-page-bar is-v29|publication-library-page-bar__hero|publication-library-page-bar__hub/, "Legacy Hero Band and Split Hub must not remain the primary Page command layout");
assert.doesNotMatch(page, /publication-library-page-bar__page|publication-library-page-bar__switcher/, "Page bar must not revive a separate labeled Page dropdown");
assert.match(css, /Publication Library v30[\s\S]*\.publication-library-page-bar__compact[\s\S]*\.publication-library-page-bar__sync/, "Calm Compact must style a single lean command strip");
assert.match(page, /publications\.length === 0 \?\s*\(?\s*<section className="publication-library-empty-desk"[\s\S]*emptyStageHint/, "An empty stage must stay quiet because the Page bar owns the sync action");
assert.doesNotMatch(page, /publication-library-editorial-sync/, "Empty Desk replaces the two-column first-sync landing as the Library entry");
assert.match(page, /setSyncSetupOpen\(publicationPayload\.publications\.length === 0\)/, "Load must close sync setup when the Page already has publications so the Desk opens immediately");
assert.match(page, /publication-library-studio is-v21[\s\S]*is-empty|className=\{`publication-library-studio is-v21\$\{[^}]*is-empty/, "Publications must render the Desk shell even when the library is empty");
assert.doesNotMatch(page, /syncSetupOpen && discovered === null/, "Empty Desk must not gate the Library behind a separate first-sync landing");
assert.doesNotMatch(page, /publication-library-empty-desk[\s\S]*syncReels|publication-library-stage-quiet-empty[\s\S]*syncReels/, "The empty stage must not duplicate the Page bar Sync action");
assert.match(page, /publication-library-empty-desk__guide[\s\S]*emptyStageTitle[\s\S]*emptyGuideStep/, "Empty Desk must explain the path with a guide panel, not a marketing landing");
assert.match(page, /publication-library-empty-desk__ghost[\s\S]*publication-library-empty-desk__ghost-row[\s\S]*publication-library-empty-desk__ghost-focus/, "Empty Desk must preview the future worklist and focus panes as a ghost silhouette");
assert.match(page, /publications\.length === 0[\s\S]{0,220}publication-library-tools__empty-cue|tools__empty-cue[\s\S]*emptyToolsCue/, "An empty Library must hide search and zero-count chips instead of showing a disabled filter strip");
assert.match(css, /Publication Library v23[\s\S]*\.publication-library-empty-desk__guide[\s\S]*\.publication-library-empty-desk__ghost/, "Empty Desk creative layout must style the guide and ghost preview panes");
assert.match(page, /publications\.length > 0 \|\| discovered !== null \?\s*\(?\s*<nav[\s\S]*workspaceLabel/, "Library and Discovered tabs must stay hidden until real data exists");
assert.match(page, /type PublicationWorkspaceMode = "LIBRARY" \| "DISCOVERED"[\s\S]*setWorkspaceMode\("DISCOVERED"\)/, "A successful sync must switch the Publication Stage to the Discovered workspace");
assert.match(page, /type PageSyncStatus = "PRE_SYNC" \| "SYNCING" \| "SYNCED" \| "HAS_NEW" \| "UP_TO_DATE" \| "HAS_MORE" \| "FAILED"/, "Page sync must expose an explicit state model");
assert.match(page, /publication-library-filter-chips[\s\S]*discoveryView === "PENDING"[\s\S]*discoveryView === "IMPORTED"|setDiscoveryView\("PENDING"\)[\s\S]*setDiscoveryView\("IMPORTED"\)/, "Discovery must separate Reels that are not in the library from imported Reels");
assert.match(page, /setPageSyncStatus\("SYNCING"\)[\s\S]*setPageSyncStatus\(payload\.next_cursor \? "HAS_MORE"[\s\S]*setPageSyncStatus\("FAILED"\)/, "Sync lifecycle must expose pending, success, pagination, and failure states");
assert.match(page, /showLibraryWorkspace[\s\S]*!selected && publications\[0\][\s\S]*openPublication\(publications\[0\]\)/, "Returning to Library must select the first publication when the inspector has no context");
assert.match(page, /publicationQuery[\s\S]*publicationFilter[\s\S]*filteredPublications/, "Publication roster must support local search and operational filters");
assert.match(page, /publication-library-worklist[\s\S]*publication-library-worklist-row[\s\S]*linkedState[\s\S]*trackedState/, "Every publication worklist row must expose external, draft-link, and tracking state");
assert.match(page, /publication-library-focus[\s\S]*publication-library-inspector-tabs/, "The focus pane must host the selected preview and inspector tabs");
assert.match(page, /type InspectorTab = "OVERVIEW" \| "INSIGHTS" \| "TRACKING" \| "CLASSIFY"/, "Inspector must tab Overview, Insights, Tracking, and Classify instead of one long form");
assert.match(page, /publication-library-inspector-tabs[\s\S]*inspectorTab === "OVERVIEW"[\s\S]*inspectorTab === "INSIGHTS"/, "Inspector tabs must switch the visible inspection surface");
assert.match(page, /publication-library-inspector-facts[\s\S]*native_product_placement_status[\s\S]*affiliate_comment_status/, "Publication inspector must expose lifecycle and monetization context already available in the contract");
assert.match(page, /latest_like_count[\s\S]*latest_comment_count[\s\S]*latest_share_count/, "Insights summary must include the available audience interaction counters");
assert.match(page, /type ReelImportState = "READY" \| "IMPORTING" \| "IMPORTED" \| "FAILED"/, "Each discovered Reel must have an explicit import state");
assert.match(page, /publication-library-reel-status/, "Each discovered Reel must expose its import state visually");
assert.match(page, /retryImport/, "Failed imports must remain retryable");
assert.match(page, /discoverFacebookReels/, "Library must discover existing Page Reels");
assert.match(page, /importDiscoveredFacebookReel/, "Library must import external Reel evidence");
assert.match(page, /linkPublicationDraft/, "Library must allow optional draft linking after import");
assert.match(page, /fetchPublicationGrowthSummary|fetchPublicationMetricSnapshots/, "Library must load publication metrics");
assert.match(page, /preflightFacebookInsights/, "Insights must remain fail-closed behind preflight");
assert.match(page, /failedPreflightChecks/, "Blocked Insights readiness must expose the failed checks");
assert.match(page, /readinessBlockedDetail/, "Blocked readiness must explain how many checks need attention");
assert.match(page, /authorizeNetwork/, "One-shot network collection must require operator authorization");
assert.match(page, /collectFacebookInsightsOnce/, "Library must support explicit one-shot collection");
assert.match(page, /fetchJob\(jobId\)/, "Library must poll the queued Insights job instead of leaving metrics stale");
assert.match(page, /fetchPublicationGrowthSummary\(publicationId\)[\s\S]*fetchPublicationMetricSnapshots\(publicationId\)/, "A completed Insights job must refresh growth and snapshots");
assert.match(page, /publication-library-job-status/, "Insights job state must remain visible while collection runs or fails");
assert.match(page, /insightsQueueDelayed[\s\S]*collectionWorkerDelayed/, "A queued Insights job must warn when no worker claims it within the threshold");
assert.match(page, /velocity_status[\s\S]*minimum_velocity_interval_seconds[\s\S]*next_stable_measurement_at/, "Unstable Views per hour must be withheld with a next-measurement explanation");
assert.match(page, /baselineSaved/, "The first completed collection must be labeled as a saved baseline");
assert.match(page, /partialEngagementDetail/, "Partial Facebook counters must be explained instead of looking complete");
assert.match(page, /enablePublicationMetricTracking[\s\S]*pausePublicationMetricTracking[\s\S]*resumePublicationMetricTracking/, "Library must expose enable, pause and resume tracking controls");
assert.match(page, /fetchPublicationMetricSchedule[\s\S]*trackingSnapshotUpdated/, "Active tracking must poll its durable schedule and refresh snapshots");
assert.match(page, /FACEBOOK_INSIGHTS_AUTO_TRACKING_APPROVED|authorizeTracking/, "Recurring reads must require explicit operator authorization");
assert.match(page, /\/publishing\/accounts/, "An empty Library must link to Facebook Page setup on the same Operator surface");
assert.match(page, /type LibraryView = "PUBLICATIONS" \| "TRACKING" \| "INTELLIGENCE"/, "Primary lanes must be Library, Monitor, and Intelligence — not six competing tabs");
assert.match(page, /type IntelligenceLane = "CLASSIFICATION" \| "TAXONOMY" \| "PRODUCT_MATCHING" \| "OPPORTUNITIES"/, "Intelligence must nest classification, taxonomy, matching, and opportunities as a secondary lane");
assert.match(page, /PublicationTrackingMonitor/, "Library must render the centralized Tracking Monitor");
assert.match(page, /openPublicationByContext[\s\S]*platformAccountId[\s\S]*openPublication\(publication\)/, "Monitor and classification queue must open a publication in its owning Page context");
assert.match(page, /publication-library-intelligence-nav/, "Intelligence lane must expose a secondary nav instead of primary tabs");

assert.match(trackingMonitor, /fetchPublicationMetricTrackingMonitor/, "Tracking Monitor must use the aggregated monitor endpoint");
assert.match(trackingMonitor, /pausePublicationMetricTracking[\s\S]*resumePublicationMetricTracking/, "Tracking Monitor must expose pause and resume controls");
assert.match(trackingMonitor, /tracking-monitor-drawer/, "Tracking Monitor must expose schedule and snapshot details");
assert.match(page, /classificationTab/, "Library must expose the content classification queue under Intelligence");
assert.match(page, /ContentClassificationQueue/, "Library must render the content classification queue");
assert.match(page, /ContentTaxonomyManager/, "Library must render the operator taxonomy manager");
assert.doesNotMatch(page, /AI_CONFIG|<ContentAiConfiguration/, "Workspace AI configuration must not remain embedded in Publication Library");
assert.match(page, /href="\/publishing\/settings\/content-intelligence"[\s\S]*configureAi/, "Publication Library must keep a shortcut to workspace Content AI settings");
assert.match(contentIntelligenceSettingsRoute, /ContentIntelligenceSettingsPage/, "Publishing settings must expose the canonical Content Intelligence route");
assert.match(contentIntelligenceSettingsPage, /OperatorStudioShell[\s\S]*ContentAiConfiguration/, "Content Intelligence settings must stay on the unified frontend Operator surface");
assert.match(classificationPanel, /runPublicationContentClassification[\s\S]*decideContentClassification/, "Publication inspector must support classify, approve, and override");
assert.match(classificationPanel, /evidence_json/, "Classification review must expose persisted evidence");
assert.match(classificationQueue, /fetchContentClassificationQueue[\s\S]*lowConfidenceOnly/, "Classification queue must support server-side review filters");
assert.match(classificationQueue, /getClassificationSourcePresentation[\s\S]*classification-source-badge/, "Classification queue must identify AI, local, and fallback results on each topic row");
assert.match(classificationPanel, /publication-classification-runtime[\s\S]*classificationSourceTitle/, "Classification review must expose provider, model, and prompt provenance");
assert.match(classificationPresentation, /"AI" \| "LOCAL" \| "AI_FALLBACK"[\s\S]*network_used[\s\S]*fallback_from/, "Classification source presentation must derive explicit runtime provenance from persisted metadata");
assert.match(taxonomyManager, /createContentTopic[\s\S]*updateContentTopic/, "Taxonomy manager must support creating and editing topics");
assert.match(contentAiConfiguration, /fetchContentAiConfig[\s\S]*updateContentAiConfig[\s\S]*testContentAi/, "Content AI must support loading, saving, and testing its provider configuration");
assert.match(contentAiConfiguration, /createContentAiPrompt[\s\S]*updateContentAiPrompt[\s\S]*activateContentAiPrompt/, "Content AI must expose versioned prompt profiles and rollback activation");
assert.match(contentAiConfiguration, /HYBRID[\s\S]*AI_ONLY[\s\S]*LOCAL_ONLY/, "Content AI must expose explicit runtime modes");
assert.match(affiliateCatalogPage, /createAffiliateProduct[\s\S]*bulkImportAffiliateProducts[\s\S]*updateAffiliateProduct/, "Affiliate Catalog must support create, CSV import, and active-state updates");
assert.match(affiliateCatalogPage, /openEditForm[\s\S]*editingProductId[\s\S]*updateAffiliateProduct\(productId, changedPayload\)/, "Affiliate Catalog must support full product editing through a minimal changed-field PATCH");
assert.match(affiliateCatalogPage, /affiliateCatalog\.imageUrl[\s\S]*image_url[\s\S]*affiliate-catalog-image-preview/, "Affiliate Catalog must expose and preview a product image URL");
assert.match(affiliateCatalogPage, /uploadAffiliateProductImage[\s\S]*uploadImage[\s\S]*type="file"/, "Affiliate Catalog must support uploading a product image from the operator computer");
assert.match(affiliateCatalogPage, /accept="image\/jpeg,image\/png,image\/webp"/, "Product image upload must limit the file chooser to supported formats");
assert.match(affiliateCatalogPage, /image_url: pendingImageUrlRef\.current \?\? draft\.image_url[\s\S]*pendingImageUrlRef\.current = uploaded\.image_url/, "Saving must use the latest uploaded image even before draft rendering settles");
assert.match(affiliateCatalogPage, /changedPayload[\s\S]*draftValueChanged[\s\S]*updateAffiliateProduct\(productId, changedPayload\)/, "Editing must PATCH only changed product fields so unrelated stale data cannot block an image replacement");
assert.match(affiliateCatalogPage, /persisted\.image_url[\s\S]*nextDraft\.image_url[\s\S]*imagePersistError/, "The editor must remain open if the saved product does not confirm the selected image");
assert.match(affiliateCatalogPage, /setProducts\(\(current\)[\s\S]*product\.id === persisted\.id \? persisted : product/, "A saved image replacement must update the catalog row immediately from the persisted response");
assert.match(affiliateCatalogPage, /edit_product_id[\s\S]*deepLink[\s\S]*affiliateUrlInputRef/, "Affiliate URL warnings must deep-link to the selected product and focus the correct catalog field");
assert.match(affiliateCatalogPage, /isPublicHttpsUrl\(draft\.affiliate_url\)[\s\S]*affiliateUrlInvalid/, "Affiliate Catalog must block local, HTTP, and image URLs in the Affiliate URL field");
assert.match(publicHttpsUrl, /url\.protocol !== "https:"[\s\S]*hostname === "localhost"/, "Public URL validation must reject non-HTTPS and local origins");
assert.match(affiliateCatalogPage, /affiliateImagePreviewUrl\(draft\.image_url\)[\s\S]*affiliateImagePreviewUrl\(product\.image_url\)/, "Catalog previews must render app-owned images through the current web origin");
assert.match(affiliateImagePresentation, /AFFILIATE_ASSET_PATH[\s\S]*parsed\.pathname\.startsWith\("\/api\/"\)/, "App-owned image presentation must replace stale tunnel origins with the local API rewrite");
assert.match(affiliateCatalogPage, /unknownTopicCodes[\s\S]*topic_codes[\s\S]*topic_ids/, "Affiliate Catalog import must resolve CSV topic codes to taxonomy ids and reject unknown codes");
assert.match(affiliateCatalogCsv, /quoted|parseCsvRows|topic_codes/, "Affiliate Catalog CSV parser must support quoted cells and topic codes");
assert.match(affiliateCatalogSettingsRoute, /AffiliateCatalogSettingsPage/, "Affiliate Catalog must have a canonical Publishing Settings route");
assert.match(affiliateMatchingQueue, /runAffiliateProductMatch[\s\S]*decideAffiliateProductMatch/, "Product Matching must support durable runs and operator decisions");
assert.match(affiliateMatchingQueue, /noAutoPlacement|reviewSafety/, "Product Matching must communicate that no affiliate placement is automatic");
assert.doesNotMatch(affiliateMatchingQueue, /â€”|Â·/, "Product Matching must not ship mojibake punctuation");
assert.match(page, /PRODUCT_MATCHING[\s\S]*AffiliateProductMatchingQueue/, "Publication Library must expose the Product Matching tab");
assert.match(page, /OPPORTUNITIES[\s\S]*AffiliateOpportunityRanking/, "Publication Library must expose the Opportunity Ranking tab");
assert.match(opportunityRanking, /fetchAffiliateOpportunityQueue[\s\S]*runPublicationGrowthScore/, "Opportunity Ranking must load reviewed matches and run durable Growth Score jobs");
assert.match(opportunityRanking, /growth_assessment[\s\S]*affiliate_fit_score[\s\S]*recommendation/, "Opportunity Ranking must show Growth Score and Affiliate Fit as separate signals");
assert.match(opportunityRanking, /noCombinedScore|separateScores/, "Opportunity Ranking must explicitly reject combined scores and automatic placement");
assert.match(opportunityRanking, /AffiliateCommentPlacementPanel[\s\S]*affiliateComment\.prepare/, "Priority opportunities must expose the affiliate comment preview panel");
assert.match(affiliateCommentPanel, /previewAffiliateCommentPlacement[\s\S]*approveAffiliateCommentPlacement/, "Affiliate comment panel must support Preview then Approve & Post");
assert.match(affiliateCommentPanel, /confirmPost|approvePost/, "Affiliate comment posting must require explicit operator confirmation");
assert.match(affiliateCommentPanel, /comment_source[\s\S]*comment_message_template_override[\s\S]*replaces_placement_id[\s\S]*beginEdit/, "Draft and failed comment previews must support audited shared/custom source revisions");
assert.match(affiliateCommentPanel, /\["DRAFT", "FAILED"\]/, "Only safe pre-post states may expose preview editing");
assert.match(affiliateCommentPanel, /attachment_image_url[\s\S]*affiliate-comment-attachment-source[\s\S]*selected_product_image_url/, "Affiliate comment preview must show the immutable attachment and current catalog image source");
assert.match(affiliateCommentPanel, /affiliateImagePreviewUrl\(placement\.attachment_image_url\)[\s\S]*affiliateImagePreviewUrl\(item\.selected_product_image_url\)/, "Affiliate comment images must remain visible when a stored tunnel origin expires");
assert.match(affiliateCommentPanel, /changeTemplate[\s\S]*templateDefault[\s\S]*templateTestOnly/, "Affiliate comment preview must allow explicit default and test-only template version selection");
assert.match(affiliateCommentPanel, /itemTemplateChoiceId[\s\S]*applyTemplateToItem[\s\S]*replaceCurrent: true[\s\S]*useSelectedTemplate/, "Each draft must allow a saved template version to be selected and applied to that item as a new revision");
assert.match(affiliateCommentPanel, /renderCommentMethodChooser[\s\S]*methodStepTitle[\s\S]*sharedTemplateMode[\s\S]*customCommentMode/, "Each item must expose a clear beginner-friendly choice between shared and custom comment sources");
assert.match(affiliateCommentPanel, /customMessageTemplate[\s\S]*availableVariables[\s\S]*extractedAffiliateUrl[\s\S]*extractedProductImage[\s\S]*createCustomDraft/, "Custom comments must support variables and separately extracted URL/image inputs before creating a draft");
assert.match(affiliateCommentPanel, /customMessageReady[\s\S]*selectedProductAffiliateUrlIsPublic[\s\S]*customMessageTemplate/, "A custom comment recipe must allow the system to supply the item Affiliate URL automatically");
assert.match(affiliateCommentPanel, /affiliateUrlAutoAppended|affiliate_url.*optional|customVariablesHint/, "Custom comment guidance must explain that Affiliate URL insertion is automatic and the variable is optional");
assert.match(affiliateCommentPanel, /isPublicHttpsUrl[\s\S]*readinessChecks[\s\S]*readinessReady[\s\S]*resolveReadinessFirst/, "Affiliate comment posting must expose and enforce client-side readiness checks");
assert.match(affiliateCommentPanel, /Existing placements are immutable snapshots[\s\S]*selectedProductAffiliateUrl = item\.selected_product_affiliate_url/, "Replacing an old draft must validate against the current catalog Affiliate URL instead of a stale placement snapshot");
assert.match(affiliateCommentPanel, /renderAffiliateUrlRequirement[\s\S]*affiliateUrlBlockedTitle[\s\S]*fixAffiliateUrl[\s\S]*affiliate-comment-url-blocker/, "Affiliate comment drafts must explain and link the required public URL when the action is blocked");
assert.match(affiliateCommentPanel, /fetchAffiliateCommentHistory[\s\S]*create_another_comment[\s\S]*previous_posted_placement_id/, "A posted comment must submit a separately audited next-comment contract");
assert.match(affiliateCommentPanel, /beginAnotherComment[\s\S]*createAnother/, "A posted comment must expose the operator action for preparing the next comment");
assert.match(affiliateCommentPanel, /postedHistory[\s\S]*affiliate-comment-history/, "Multiple comments must expose an auditable posted-comment history");
assert.match(affiliateCommentPanel, /verifyAffiliateCommentPlacement[\s\S]*fetchJob[\s\S]*Check now|checkNow/, "Posted comment history must support an explicit verification job and polling");
assert.match(affiliateCommentPanel, /affiliate-comment-verification-summary[\s\S]*verification-badge[\s\S]*verificationStatus/, "Verification results must expose colored status and separate comment/link details");
assert.match(affiliateCommentPanel, /history\.can_post_now[\s\S]*readinessPostingWindow/, "A subsequent comment must expose a safe posting-window readiness gate");
assert.doesNotMatch(opportunityRanking, /opportunity-ranking-info-note/, "Opportunity ranking must not show a persistent score note that can be mistaken for an action result");
assert.match(affiliateCommentPanel, /disabled=\{!templateId \|\| !selectedProductAffiliateUrlIsPublic\}/, "Template preview generation must require a public Affiliate URL without requiring an optional disclosure value");
assert.match(affiliateCommentTemplatesPage, /fetchAffiliateCommentTemplates[\s\S]*reviseAffiliateCommentTemplate[\s\S]*activateAffiliateCommentTemplate[\s\S]*deleteAffiliateCommentTemplate/, "Affiliate Comment Settings must support loading, versioning, activating, and deleting templates");
assert.match(affiliateCommentTemplatesPage, /createAffiliateCommentTemplate/, "Affiliate Comment Settings must create a first template");
assert.match(affiliateCommentTemplatesPage, /save\(activateAfterSave = false\)[\s\S]*activateAffiliateCommentTemplate\(saved\.id\)/, "Affiliate Comment Settings must support saving a version and saving then activating it");
assert.match(affiliateCommentTemplatesPage, /selectedTemplate && !selectedTemplate\.is_active/, "Affiliate Comment Settings must only offer direct activation for an inactive selected version");
assert.match(affiliateCommentTemplatesPage, /message_template[\s\S]*attach_product_image[\s\S]*product_image/, "Affiliate Comment Settings must expose message variables and separate image attachment policy");
assert.match(affiliateCommentTemplatesRoute, /AffiliateCommentTemplatesSettingsPage/, "Affiliate Comment Templates must have a canonical Publishing Settings route");

assert.match(api, /facebook-reels/, "Web API must expose Page Reel discovery");
assert.match(api, /comment_source[\s\S]*comment_message_template_override/, "Web API must support audited shared-template and custom-item comment modes");
assert.match(api, /facebook-discovery-import/, "Web API must expose discovery import");
assert.match(api, /Array\.isArray\(body\.detail\)/, "Web API errors must surface FastAPI validation details instead of a bare 422");
assert.match(api, /draft-link/, "Web API must expose later draft linking");
assert.match(api, /metric-schedule/, "Web API must expose publication tracking schedules");
assert.match(api, /FACEBOOK_INSIGHTS_AUTO_TRACKING_APPROVED/, "Schedule API calls must carry explicit recurring-read confirmation");
assert.match(api, /analytics\/metric-tracking-monitor/, "Web API must expose the centralized tracking monitor endpoint");
assert.match(api, /content-classifications\/review-queue/, "Web API must expose the classification review queue endpoint");
assert.match(api, /content-intelligence\/ai-config[\s\S]*CONTENT_CLASSIFICATION_AI_APPROVED/, "Content AI calls must use workspace config and explicit external-network authorization");
assert.match(api, /affiliate-products[\s\S]*bulk-import[\s\S]*affiliate-product-matches\/review-queue[\s\S]*affiliate-product-match-jobs[\s\S]*affiliate-product-matches\//, "Web API must expose catalog, matching queue, durable run, and decision endpoints");
assert.match(api, /uploadAffiliateProductImage[\s\S]*FormData[\s\S]*affiliate-product-images/, "Web API must submit affiliate product image files as multipart data");
assert.match(api, /growth-score-jobs[\s\S]*affiliate-opportunities\/review-queue/, "Web API must expose durable Growth Score and Opportunity Ranking endpoints");
assert.match(api, /affiliate-comment-placement\/preview[\s\S]*affiliate-comment-placements\//, "Web API must expose affiliate comment preview and approval endpoints");
assert.match(api, /fetchAffiliateCommentHistory[\s\S]*affiliate-comment-placements/, "Web API must expose affiliate comment history and repeat-post policy state");
assert.match(api, /verifyAffiliateCommentPlacement[\s\S]*verification-jobs[\s\S]*authorize_network/, "Web API must expose explicit affiliate comment verification authorization");
assert.match(api, /affiliate-comment-templates[\s\S]*activateAffiliateCommentTemplate[\s\S]*deleteAffiliateCommentTemplate/, "Web API must expose versioned affiliate comment template endpoints");
assert.match(nav, /\/publishing\/publications/, "Publication Library must be available in operator navigation");
assert.match(nav, /sectionPublishingSettings[\s\S]*\/publishing\/settings\/content-intelligence/, "Content Intelligence must live under Publishing Settings navigation");
assert.match(nav, /sectionPublishingSettings[\s\S]*\/publishing\/settings\/affiliate-catalog/, "Affiliate Catalog must live under Publishing Settings navigation");
assert.match(css, /\.publication-library-page/, "Library must have scoped layout styles");
assert.match(css, /Publication Library v6[\s\S]*\.publication-library-page-dock[\s\S]*\.publication-library-stage-empty[\s\S]*\.publication-library-runway/, "Library must style the new vertical Page Dock and Publication Stage layout");
assert.match(css, /Publication Library v7[\s\S]*height: calc\(100vh - 142px\)[\s\S]*\.publication-library-imported-group[\s\S]*overflow-y: auto/, "Synced Publication Workspace must remain viewport-bounded with compact discovery rows and internal scrolling");
assert.match(css, /Publication Library v23[\s\S]*\.publication-library-empty-desk[\s\S]*\.publication-library-empty-desk__ghost/, "Empty Desk must style the guide-and-ghost composition inside the Desk shell");
assert.match(css, /Publication Library v17[\s\S]*\.publication-library-page-sync-state\.is-syncing[\s\S]*\.publication-library-page-sync-state\.is-failed[\s\S]*\.publication-library-discovery-tabs/, "Sync and import states must have distinct project-aligned visual treatments");
assert.match(css, /Publication Library v19[\s\S]*\.publication-library-stage-quiet-empty|Publication Library v22[\s\S]*\.publication-library-stage-quiet-empty/, "The empty result stage must use a restrained, non-interactive treatment");
assert.match(css, /Publication Library v20[\s\S]*\.publication-library-page-bar[\s\S]*\.publication-library-kpi-strip[\s\S]*\.publication-library-gallery[\s\S]*\.publication-library-inspector-tabs/, "Hybrid redesign must style the page bar, KPI strip, media gallery, and inspector tabs");
assert.match(css, /Publication Library v21[\s\S]*\.publication-library-tools[\s\S]*\.publication-library-desk[\s\S]*\.publication-library-worklist[\s\S]*\.publication-library-focus/, "Desk redesign must style the tools row, worklist, and focus pane");
assert.match(css, /\.publication-library-reel-grid/, "Library must have responsive Reel discovery styles");
assert.match(css, /\.publication-library-preflight-result/, "Insights preflight must have a visible result panel");
assert.match(css, /\.publication-library-job-status\.is-retryable[\s\S]*\.publication-library-job-status\.is-completed[\s\S]*\.publication-library-job-status\.is-failed/, "Insights job states must use distinct colors");
assert.match(css, /\.publication-library-velocity-guidance/, "Velocity quality guidance must have a visible callout");
assert.match(css, /\.publication-library-tracking/, "Auto tracking controls must have a scoped visual section");
assert.match(css, /\.publication-library-main-tabs/, "Publication Library must have primary view tabs");
assert.match(css, /\.tracking-health-badge\.is-healthy[\s\S]*\.tracking-health-badge\.is-delayed[\s\S]*\.tracking-health-badge\.is-blocked/, "Tracking health states must use distinct colors");
assert.match(css, /\.tracking-monitor-drawer/, "Tracking details must have a responsive drawer layout");
assert.match(css, /\.publication-classification/, "Publication inspector must have scoped classification styles");
assert.match(css, /\.classification-queue-table/, "Classification queue must have responsive table styles");
assert.match(css, /\.classification-source-badge\.is-ai[\s\S]*\.classification-source-badge\.is-local[\s\S]*\.classification-source-badge\.is-ai_fallback/, "AI, local, and fallback source badges must use distinct colors");
assert.match(css, /\.content-taxonomy-page/, "Taxonomy manager must have scoped styles");
assert.match(css, /\.content-ai-page[\s\S]*\.content-ai-prompts-layout/, "Content AI configuration must have scoped responsive styles");
assert.match(css, /article\.is-ready[\s\S]*article\.is-importing[\s\S]*article\.is-imported[\s\S]*article\.is-failed/, "Reel import states must use distinct card colors");
assert.match(css, /\.affiliate-catalog-page[\s\S]*\.affiliate-matching-page/, "Affiliate Catalog and Product Matching must have scoped styles");
assert.match(css, /\.affiliate-matching-table td > strong \+ small[\s\S]*display: block/, "Product Matching topic status must render on a separate line");
assert.match(css, /\.affiliate-matching-status\.is-needs_review[\s\S]*\.affiliate-matching-status\.is-approved[\s\S]*\.affiliate-matching-status\.is-rejected[\s\S]*\.affiliate-matching-status\.is-overridden/, "Product Matching decisions must use distinct colors");
assert.match(css, /\.opportunity-ranking-page[\s\S]*\.opportunity-recommendation-cell > span\.is-priority[\s\S]*\.is-do_not_place/, "Opportunity Ranking must have scoped styles and distinct recommendation colors");
assert.match(css, /\.affiliate-comment-panel[\s\S]*\.affiliate-comment-status\.is-posted[\s\S]*\.affiliate-comment-preview/, "Affiliate comment preview must have scoped status and preview styles");
assert.match(css, /\.affiliate-comment-template-layout[\s\S]*\.affiliate-comment-template-editor/, "Affiliate Comment Settings must have scoped template editor styles");
assert.match(css, /\.affiliate-comment-locked-url[\s\S]*\.affiliate-comment-edit-button/, "Preview editing must clearly separate the locked product URL from editable copy");
assert.match(css, /\.affiliate-catalog-image-preview[\s\S]*\.affiliate-comment-attachment-source/, "Catalog and comment attachment images must have scoped preview styles");
assert.match(css, /\.affiliate-catalog-upload-panel[\s\S]*input\[type="file"\]/, "Affiliate Catalog image upload must have scoped responsive styles");
assert.match(en, /"publicationLibrary"/, "English translations must cover the Library");
assert.match(vi, /"publicationLibrary"/, "Vietnamese translations must cover the Library");
assert.match(en, /"trackingMonitor"/, "English translations must cover Tracking Monitor");
assert.match(vi, /"trackingMonitor"/, "Vietnamese translations must cover Tracking Monitor");
assert.match(en, /"productMatchingTab"[\s\S]*"affiliateCatalog"[\s\S]*"affiliateMatching"/, "English translations must cover Product Matching and Affiliate Catalog");
assert.match(vi, /"productMatchingTab"[\s\S]*"affiliateCatalog"[\s\S]*"affiliateMatching"/, "Vietnamese translations must cover Product Matching and Affiliate Catalog");
assert.match(en, /"opportunityRankingTab"[\s\S]*"opportunityRanking"/, "English translations must cover Opportunity Ranking");
assert.match(vi, /"opportunityRankingTab"[\s\S]*"opportunityRanking"/, "Vietnamese translations must cover Opportunity Ranking");
assert.match(en, /"affiliateComment"[\s\S]*"approvePost"/, "English translations must cover affiliate comment approval");
assert.match(vi, /"affiliateComment"[\s\S]*"approvePost"/, "Vietnamese translations must cover affiliate comment approval");
assert.match(en, /"templateTestOnly"[\s\S]*"readinessTitle"[\s\S]*"resolveReadinessFirst"/, "English translations must cover template testing and posting readiness");
assert.match(vi, /"templateTestOnly"[\s\S]*"readinessTitle"[\s\S]*"resolveReadinessFirst"/, "Vietnamese translations must cover template testing and posting readiness");
assert.match(en, /"itemTemplateTitle"[\s\S]*"applyTemplateRegenerate"[\s\S]*"customizePreviewHint"/, "English translations must distinguish item template assignment from preview customization");
assert.match(vi, /"itemTemplateTitle"[\s\S]*"applyTemplateRegenerate"[\s\S]*"customizePreviewHint"/, "Vietnamese translations must distinguish item template assignment from preview customization");
assert.match(en, /"affiliateCommentTemplates"[\s\S]*"attachImage"[\s\S]*"productImageVariable"/, "English translations must cover affiliate comment templates");
assert.match(vi, /"affiliateCommentTemplates"[\s\S]*"attachImage"[\s\S]*"productImageVariable"/, "Vietnamese translations must cover affiliate comment templates");
assert.match(en, /"affiliateCommentTemplates"[\s\S]*"saveAndActivate"[\s\S]*"deleteConfirm"/, "English translations must cover affiliate comment template save and delete actions");
assert.match(vi, /"affiliateCommentTemplates"[\s\S]*"saveAndActivate"[\s\S]*"deleteConfirm"/, "Vietnamese translations must cover affiliate comment template save and delete actions");
assert.match(en, /"commentSourceTitle"[\s\S]*"customMessageTemplate"[\s\S]*"extractedProductImage"/, "English translations must cover comment source switching and custom variable rendering");
assert.match(vi, /"commentSourceTitle"[\s\S]*"customMessageTemplate"[\s\S]*"extractedProductImage"/, "Vietnamese translations must cover comment source switching and custom variable rendering");
assert.match(en, /"uploadImage"[\s\S]*"chooseImage"[\s\S]*"imageUploaded"/, "English translations must cover product image upload");
assert.match(vi, /"uploadImage"[\s\S]*"chooseImage"[\s\S]*"imageUploaded"/, "Vietnamese translations must cover product image upload");

console.log("publication-library tests passed");
